### ISSUE TITLE
请问这个提示是因为山姆服务器的原因吗？

### ISSUE THREAD

**Issue by asakali** [robGoods/sams#1]
![20220413-0](https://user-images.githubusercontent.com/17283599/163187013-298d415a-1b50-47a7-9549-2a59879f9993.png)

在21点左右，提示有可用时段，卡了一会后出以上提示。

**Comment by jonaszhouC** [comment]
请教一下怎么抓包的啊，我用fiddler 山姆app无网络

**Comment by iscod** [comment]
> ![20220413-0](https://user-images.githubusercontent.com/17283599/163187013-298d415a-1b50-47a7-9549-2a59879f9993.png)
> 
> 在21点左右，提示有可用时段，卡了一会后出以上提示。

21点山姆访问经常超时，刚更新了项目可以再试下

**Comment by iscod** [comment]
> 请教一下怎么抓包的啊，我用fiddler 山姆app无网络

我用的charles

**Comment by iscod** [comment]
> 经常超时，刚更新了项目可以再试

  目前测试很少超时，且设置了超时后程序会进行重试
