### ISSUE TITLE
如何下配送时间为周六的订单

### ISSUE THREAD

**Issue by gyf19** [robGoods/sams#11]
![image](https://user-images.githubusercontent.com/233857/163417733-465fd423-6b03-40af-9849-b4d69fed302f.png)

getCapacityData 接口刷不出来， 周六的配送时间。
@iscod  了解一下

**Comment by KirbyInGitHub** [comment]
我这边昨天晚上9点获取到的就是周五的可用时间，今天晚上9点获取到的就是周六的可用时间，看起来浦东的山姆全城配的运力就是隔一天的。
