### ISSUE TITLE
不会运行go。。。

### ISSUE THREAD

**Issue by Looper0331** [robGoods/sams#12]
抓好包了，差数也改好了，不会运行。。。。

<img src="https://s1.328888.xyz/2022/04/15/ihZug.png" alt="ihZug.png" border="0" />

**Comment by iscod** [comment]
> 抓好包了，差数也改好了，不会运行。。。。
> 
> ![ihZug.png](https://camo.githubusercontent.com/bb602dfd1cbecd1484391d456f52b5fa08abe81acf80cb44b326fc5cbdb56a52/68747470733a2f2f73312e3332383838382e78797a2f323032322f30342f31352f69685a75672e706e67)

> 抓好包了，差数也改好了，不会运行。。。。
> 
> ![ihZug.png](https://camo.githubusercontent.com/bb602dfd1cbecd1484391d456f52b5fa08abe81acf80cb44b326fc5cbdb56a52/68747470733a2f2f73312e3332383838382e78797a2f323032322f30342f31352f69685a75672e706e67)

你这代码不是最新的吧？

**Comment by Looper0331** [comment]
是最新的，除了main.go文件修改以外，应该没有其他地方需要修改了吧。。。
<img src="https://s1.328888.xyz/2022/04/15/i4UuR.png" alt="i4UuR.png" border="0" />

**Comment by gyf19** [comment]
@Looper0331  使用最新代码

**Comment by Looper0331** [comment]
已解决，谢谢

**Comment by houkang1978** [comment]
楼主这个东西怎么用啊，我一点都不会
