### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by Nicolerobinn** [robGoods/sams#17]

**Comment by meimxn** [comment]
我也是刚刚成功下单，一并感谢
![mmexport1650107400324](https://user-images.githubusercontent.com/96645318/163672928-5c3e6bff-3224-4732-8f2e-0efc496d63fb.jpg)

**Comment by 2dot4** [comment]
浦东店可以么

> 我也是刚刚成功下单，一并感谢
> 
> ![mmexport1650107400324](https://user-images.githubusercontent.com/96645318/163672928-5c3e6bff-3224-4732-8f2e-0efc496d63fb.jpg)
> 
> 
> 
>

**Comment by binkundai** [comment]
请问成功的，几点开始运行，然后运行多久啊？

**Comment by Manchuker1120** [comment]
bark id 是device id 还是那个api.day一长串url？

**Comment by iscod** [comment]
> bark id 是device id 还是那个api.day一长串url？

url中的最后一段字符串 例如： https://api.day.app/9ePBLxEEgzTChMiKcjBmmQ/推送铃声?sound=minuet，其中的9ePBLxEEgzTChMiKcjBmmQ就是bark id

**Comment by Manchuker1120** [comment]
> > bark id 是device id 还是那个api.day一长串url？
> 
> url中的最后一段字符串 例如： [https://api.day.app/9ePBLxEEgzTChMiKcjBmmQ/推送铃声?sound=minuet，其中的9ePBLxEEgzTChMiKcjBmmQ就是bark](https://api.day.app/9ePBLxEEgzTChMiKcjBmmQ/%E6%8E%A8%E9%80%81%E9%93%83%E5%A3%B0?sound=minuet%EF%BC%8C%E5%85%B6%E4%B8%AD%E7%9A%849ePBLxEEgzTChMiKcjBmmQ%E5%B0%B1%E6%98%AFbark) id

那推送内容是在哪里修改？我bark app为什么不能修改？

**Comment by iscod** [comment]
> > > bark id 是device id 还是那个api.day一长串url？
> > 
> > 
> > url中的最后一段字符串 例如： [https://api.day.app/9ePBLxEEgzTChMiKcjBmmQ/推送铃声?sound=minuet，其中的9ePBLxEEgzTChMiKcjBmmQ就是bark](https://api.day.app/9ePBLxEEgzTChMiKcjBmmQ/%E6%8E%A8%E9%80%81%E9%93%83%E5%A3%B0?sound=minuet%EF%BC%8C%E5%85%B6%E4%B8%AD%E7%9A%849ePBLxEEgzTChMiKcjBmmQ%E5%B0%B1%E6%98%AFbark) id
> 
> 那推送内容是在哪里修改？我bark app为什么不能修改？

推送内容不就是barkid后面的吗？`推送铃声`就是内容啊

**Comment by Manchuker1120** [comment]
> > > > bark id 是device id 还是那个api.day一长串url？
> > > 
> > > 
> > > url中的最后一段字符串 例如： [https://api.day.app/9ePBLxEEgzTChMiKcjBmmQ/推送铃声?sound=minuet，其中的9ePBLxEEgzTChMiKcjBmmQ就是bark](https://api.day.app/9ePBLxEEgzTChMiKcjBmmQ/%E6%8E%A8%E9%80%81%E9%93%83%E5%A3%B0?sound=minuet%EF%BC%8C%E5%85%B6%E4%B8%AD%E7%9A%849ePBLxEEgzTChMiKcjBmmQ%E5%B0%B1%E6%98%AFbark) id
> > 
> > 
> > 那推送内容是在哪里修改？我bark app为什么不能修改？
> 
> 推送内容不就是barkid后面的吗？`推送铃声`就是内容啊
![image](https://user-images.githubusercontent.com/55781701/163831066-49539d5b-8b67-4038-8bb5-6b89e836de6a.png)
红色框 都点不动。。。

**Comment by liamyu** [comment]
robGoods有被笑到😂
