### ISSUE TITLE
提示商品限购

### ISSUE THREAD

**Issue by WeiDongTang** [robGoods/sams#18]
数量已经调整1了，还是提示商品限购

<img width="503" alt="image" src="https://user-images.githubusercontent.com/18439133/163673846-56506f9e-f597-42a8-9e8a-f5bac114969e.png">

**Comment by meimxn** [comment]
> 
是不是今天已经买过一单了

**Comment by WeiDongTang** [comment]
>

**Comment by WeiDongTang** [comment]
> 是不是今天已经买过一单了

我还以为是每单限制呢.....

**Comment by iscod** [comment]
> 数量已经调整1了，还是提示商品限购
> 
> <img alt="image" width="503" src="https://user-images.githubusercontent.com/18439133/163673846-56506f9e-f597-42a8-9e8a-f5bac114969e.png">

今天购买过了，购物车先去除了吧，后面程序也是去掉限购的再下单

**Comment by WeiDongTang** [comment]
> 



> > 数量已经调整1了，还是提示商品限购
> > <img alt="image" width="503" src="https://user-images.githubusercontent.com/18439133/163673846-56506f9e-f597-42a8-9e8a-f5bac114969e.png">
> 
> 今天购买过了，购物车先去除了吧，后面程序也是去掉限购的再下单



> > 数量已经调整1了，还是提示商品限购
> > <img alt="image" width="503" src="https://user-images.githubusercontent.com/18439133/163673846-56506f9e-f597-42a8-9e8a-f5bac114969e.png">
> 
> 今天购买过了，购物车先去除了吧，后面程序也是去掉限购的再下单

去掉了，我还以为我账号黑了呢
