### ISSUE TITLE
一直显示没运力，即使换了收获的城市也没运力但APP显示别的城市有运力

### ISSUE THREAD

**Issue by coldtea07** [robGoods/sams#2]

**Comment by iscod** [comment]
> No description provided.

这是个bug刚开始只考虑了上海地区，没根据收货地址选择运力。项目已更新，可以再试下

**Comment by coldtea07** [comment]
感谢大佬！

**Comment by coldtea07** [comment]
提示查询不到商品数据哎
![image](https://user-images.githubusercontent.com/37368885/163220038-6b61967c-49fe-4bb9-817f-fc875e19c25b.png)

**Comment by iscod** [comment]
> 提示查询不到商品数据哎 ![image](https://user-images.githubusercontent.com/37368885/163220038-6b61967c-49fe-4bb9-817f-fc875e19c25b.png)

已更新，测试了其它城市下单流程，目前可以成功

**Comment by X27192175551** [comment]
有点东西，感谢作者。

**Comment by X27192175551** [comment]
抢购成功只能付款，无法使用优惠卷，不知作者能否改进，感谢

**Comment by iscod** [comment]
> 


> 抢购成功只能付款，无法使用优惠卷，不知作者能否改进，感谢

版本稳定再说吧，目前还不稳定，更新很快

**Comment by X27192175551** [comment]
好的好的 感谢感谢

**Comment by zzjspc08** [comment]
> 好的好的 感谢感谢

哈咯 能私聊下吗

**Comment by zzjspc08** [comment]
> > 抢购成功只能付款，无法使用优惠卷，不知作者能否改进，感谢
> 
> 版本稳定再说吧，目前还不稳定，更新很快

大佬这个能在手机上用吗 身边没有电脑
