### ISSUE TITLE
我用hack版抢到了，请问会不会有封号风险?

### ISSUE THREAD

**Issue by AnAsteria** [robGoods/sams#20]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/51769809/163684566-8bc60251-8533-4977-9936-8177f6596b21.png">

一下子就抢到了，感觉心有点慌😂 不过很感谢开发者提供代码。

**Comment by cxjnevergiveup** [comment]
> 
> 
> <img width="487" alt="image" src="https://user-images.githubusercontent.com/51769809/163684566-8bc60251-8533-4977-9936-8177f6596b21.png">
> 
> 
> 
> 一下子就抢到了，感觉心有点慌😂 不过很感谢开发者提供代码。

请问抓包 是抓小程序还是直接抓app 用Charles挂代理嘛

**Comment by AnAsteria** [comment]
> > <img alt="image" width="487" src="https://user-images.githubusercontent.com/51769809/163684566-8bc60251-8533-4977-9936-8177f6596b21.png">
> > 一下子就抢到了，感觉心有点慌😂 不过很感谢开发者提供代码。
> 
> 请问抓包 是抓小程序还是直接抓app 用Charles挂代理嘛

我使用的app，然后是http catcher抓的，要下整数，油管上有教程，跟着教程来就可以（我用的ios）

**Comment by NeverArgueWithGF** [comment]
> 

能正常发货吗？

**Comment by NeverArgueWithGF** [comment]
> <img alt="image" width="487" src="https://user-images.githubusercontent.com/51769809/163684566-8bc60251-8533-4977-9936-8177f6596b21.png">
> 
> 一下子就抢到了，感觉心有点慌😂 不过很感谢开发者提供代码。

能正常发货吗？为什么heck版直接就能下 普通的就不行 没太明白 同样有点虚

**Comment by AnAsteria** [comment]
> > <img alt="image" width="487" src="https://user-images.githubusercontent.com/51769809/163684566-8bc60251-8533-4977-9936-8177f6596b21.png">
> > 一下子就抢到了，感觉心有点慌😂 不过很感谢开发者提供代码。
> 
> 能正常发货吗？为什么heck版直接就能下 普通的就不行 没太明白 同样有点虚

可以正常发货。这个原理比较奇妙，大概就是把时间戳改一改。如果你使用过postman收发数据，和那个原理差不多？

**Comment by KirbyInGitHub** [comment]
这是抢到的一周之后的运力，不是每天晚上9点释放的第二天或者隔一天的运力

**Comment by NeverArgueWithGF** [comment]
> 



> 这是抢到的一周之后的运力，不是每天晚上9点释放的第二天或者隔一天的运力

主要是担心会不会订单异常这样，给老人孩子抢吃的，太难了

**Comment by AnAsteria** [comment]
> > 
> 
> > 这是抢到的一周之后的运力，不是每天晚上9点释放的第二天或者隔一天的运力
> 
> 主要是担心会不会订单异常这样，给老人孩子抢吃的，太难了

你加我qq，897171986

**Comment by KirbyInGitHub** [comment]
> > 这是抢到的一周之后的运力，不是每天晚上9点释放的第二天或者隔一天的运力
> 
> 主要是担心会不会订单异常这样，给老人孩子抢吃的，太难了

应该不会，目前山姆的风控好像都比较松，我刚才测试了几单，山姆能正常扣减库存，上一单买掉的东西如果没库存了，下一单就会提示没有库存了。我还正常退款成功了。
