### ISSUE TITLE
请问为啥.exe文件双击了没反应

### ISSUE THREAD

**Issue by huzisir** [robGoods/sams#21]

**Comment by iscod** [comment]
> No description provided.

.exe不是双击吧？应该在cmd命令行之行吧？不然你怎么传参数？.exe我没测试，家里没win电脑😅😅😅

**Comment by huzisir** [comment]
请问auth-token是一串10位的数字吗，我用Charles抓到手机山姆app网址后没看到有auth-token的字样，还有这个auth-token要怎么修改到main.go文件里，我用cmd命令符运行main.go后提示这个go: github.com/tidwall/gjson@v1.14.0: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod": dial tcp 172.217.160.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
go: downloading github.com/tidwall/gjson v1.14.0
go: github.com/tidwall/gjson@v1.14.0: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod": dial tcp 172.217.160.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.，但我装了go环境了，抱歉我是小白，疑问比较多，才刚学会怎么用Charles，用cmd命令符运行sams-v1.0-amd64.exe提示no required module provides package sams-v1.0-amd64.exe: go.mod file not found in current directory or any parent directory; see 'go help modules'，能麻烦告诉我怎么解决吗，谢谢了

**Comment by iscod** [comment]
> 请问auth-token是一串10位的数字吗，我用Charles抓到手机山姆app网址后没看到有auth-token的字样，还有这个auth-token要怎么修改到main.go文件里，我用cmd命令符运行main.go后提示这个go: github.com/tidwall/gjson@v1.14.0: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod": dial tcp 172.217.160.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> go: downloading github.com/tidwall/gjson v1.14.0
> go: github.com/tidwall/gjson@v1.14.0: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod": dial tcp 172.217.160.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.，但我装了go环境了，抱歉我是小白，疑问比较多，才刚学会怎么用Charles，用cmd命令符运行sams-v1.0-amd64.exe提示no required module provides package sams-v1.0-amd64.exe: go.mod file not found in current directory or any parent directory; see 'go help modules'，能麻烦告诉我怎么解决吗，谢谢了

最新版本不需要修改main.go文件，只需要运行时加相应的token参数。你这个报错是go加载响应包文件是超时。

**Comment by iscod** [comment]
看一下这个，和你的报错一样https://github.com/robGoods/sams/issues/5

**Comment by huzisir** [comment]
又提示这个了go: downloading github.com/tidwall/gjson v1.14.0
go: downloading github.com/tidwall/pretty v1.2.0
go: downloading github.com/tidwall/match v1.1.1
########## 初始化 ##########
鉴权失败 token过期！！！
这是为啥，还有token参数在哪儿
<html>
<body>


Host | https://sam-material-online-1302115363.file.myqcloud.com
-- | --



</body>
</html>
这里面这个数字是吗

**Comment by iscod** [comment]
> 又提示这个了go: downloading github.com/tidwall/gjson v1.14.0 go: downloading github.com/tidwall/pretty v1.2.0 go: downloading github.com/tidwall/match v1.1.1 ########## 初始化 ########## 鉴权失败 token过期！！！ 这是为啥，还有token参数在哪儿
> 
> Host	https://sam-material-online-1302115363.file.myqcloud.com
> 这里面这个数字是吗

auth-token是在http头部的字段，抓包后看http请求的header部分

**Comment by huzisir** [comment]
那我这个头部字段就是 sam-material-online-1302115363这个吗

**Comment by huzisir** [comment]
我好像找到了241c8d961cb6491685b60fce6b34a59e，这样的是吧，那我这个怎么加到main.go里呢，一运行就提示########## 初始化 ##########
鉴权失败 token过期！！！

**Comment by figo84** [comment]
请问我找到了authtoken ，但是怎么传参数啊

**Comment by iscod** [comment]
> 请问我找到了authtoken ，但是怎么传参数啊

拉去下最新代码, 运行一下代码，xxxx换成你的authtoken就可以
```
go run main.go -authToken=xxxx
```

**Comment by huzisir** [comment]
设置通知是在go run main.go -authToken=xxxx 后面加--barkId=xxxx是吗

**Comment by iscod** [comment]
> 设置通知是在go run main.go -authToken=xxxx 后面加--barkId=xxxx是吗

对

**Comment by huzisir** [comment]
> > 设置通知是在go run main.go -authToken=xxxx 后面加--barkId=xxxx是吗
> 
> 对

感谢，感觉摸索这个又学到很多，现在就是下单老是火爆，用这个程序也不好抢了，唉，越来越难了，只能靠这个捡漏了
