### ISSUE TITLE
鉴权失败，token过期

### ISSUE THREAD

**Issue by 2dot4** [robGoods/sams#22]
已解决

**Comment by huzisir** [comment]
咋解决的，我也提示这个

**Comment by iscod** [comment]
> 咋解决的，我也提示这个

重新抓包获取新的token

**Comment by huzisir** [comment]
重新获取了C:\Users\Downloads\sams-master>go run main.go --authToken=740d926b981716f426e7559ad74bf050eac6a08b371b0c3a4c7b0fa34c172027
########## 初始化 ##########
鉴权失败 token过期！！！
还是这样

**Comment by 2dot4** [comment]
大概率是弄错了token，我原来是没找到正确的token

> 重新获取了C:\Users\Downloads\sams-master>go run main.go --authToken=740d926b981716f426e7559ad74bf050eac6a08b371b0c3a4c7b0fa34c172027
> 
> ########## 初始化 ##########
> 
> 鉴权失败 token过期！！！
> 
> 还是这样

**Comment by huzisir** [comment]
没错啊，Charles里显示的就是这个<html>
<body>


auth-token | 740d926b981716f426e7559ad74bf050eac6a08b371b0c3a4c7b0fa34c172027
-- | --



</body>
</html>

**Comment by iscod** [comment]
> 740d926b981716f426e7559ad74bf050eac6a08b371b0c3a4c7b0fa34c172027


> 没错啊，Charles里显示的就是这个
> 
> auth-token	740d926b9xxxxxxxxxxxxx

这个是对的，不过不要谁便贴自己的token

```
 go run main.go  -authToken=740d926b9xxxxx
```

我运行你的token是可以的，你代码更新到最新版本没？

**Comment by huzisir** [comment]
可以了，重新下载了最新版本就可以了，感谢大佬不厌其烦地解答，谢谢

**Comment by iscod** [comment]
> 可以了，重新下载了最新版本就可以了，感谢大佬不厌其烦地解答，谢谢

.exe文件，在cmd命令行下可以运行吗？我没win电脑，没测试

**Comment by GyllLiu** [comment]
我也现实auth-token过期，刚刚在charles抓的740d926b98xxxx

**Comment by huzisir** [comment]
> > 可以了，重新下载了最新版本就可以了，感谢大佬不厌其烦地解答，谢谢
> 
> .exe文件，在cmd命令行下可以运行吗？我没win电脑，没测
不是，运行的压缩包，.exe不能运行，小白也不会尝试，压缩包可以用就不管其它了

**Comment by aplbaoziw** [comment]
token应该怎么抓取呢 完全不会QAQ

**Comment by iscod** [comment]
> token应该怎么抓取呢 完全不会QAQ

百度一下Charles抓包，先学学抓包吧
