### ISSUE TITLE
hack版本ExpectArrivalEndTime空通不过

### ISSUE THREAD

**Issue by elwin-sh** [robGoods/sams#23]
对比看了，hack版本ExpectArrivalEndTime是""，但是这样发送到后台，提示收货时间没有填写。
hack的作用是什么呢。浦东店一直没有运力，捡漏也扫不出运力，是不释放了吗。

**Comment by iscod** [comment]
> ArrivalEndTime是""，但是这样发送到后台，提示收货时间没有填写。
> hack的作用是什么呢。浦东店一直没有运力，捡漏也扫不出运力，是

选的是全城配送吧？如果是的话那证明山姆更新了，hack版本也没啥用了。现在浦东运力及其紧张下单两三天才配送，APP上面时不时会下架所有商品防止刷单

**Comment by elwin-sh** [comment]
是全城配。

**Comment by iscod** [comment]
> 是全城配。

可能是山姆更新了系统，等我测试测试，先按版本刷吧。

**Comment by elwin-sh** [comment]
> > 是全城配。
> 
> 可能是山姆更新了系统，等我测试测试，先按版本刷吧。

不过我用的是小程序的参数，可能APP能通过。

**Comment by iscod** [comment]
> > > 是全城配。
> > 
> > 
> > 可能是山姆更新了系统，等我测试测试，先按版本刷吧。
> 
> 不过我用的是小程序的参数，可能APP能通过。

小程序还没测试过，我都是用的APP，有空我测试下
