### ISSUE TITLE
请问哪个是hack版

### ISSUE THREAD

**Issue by 2dot4** [robGoods/sams#24]
直接下载的发行版。不知道哪个是master版，哪个是hack版

**Comment by iscod** [comment]
> 直接下载的发行版。不知道哪个是master版，哪个是hack版

hack版本需要git clone下来，切换到hack版本，不过hack 有反馈说不能用了

**Comment by cxjnevergiveup** [comment]
> > 直接下载的发行版。不知道哪个是master版，哪个是hack版
> 
> 
> 
> hack版本需要git clone下来，切换到hack分支，不过hack 有反馈说不能用了

请问作者 我在app端抓包的 auth token
Run起来是这样的 挂在那边就可以啦 然后等bark通知去app付款就行了？![image](https://user-images.githubusercontent.com/52702777/163720025-93f49e71-2d76-4fbd-8e65-d60950132e59.jpeg)

**Comment by iscod** [comment]
> > > 直接下载的发行版。不知道哪个是master版，哪个是hack版
> > 
> > 
> > hack版本需要git clone下来，切换到hack分支，不过hack 有反馈说不能用了
> 
> 请问作者 我在app端抓包的 auth token Run起来是这样的 挂在那边就可以啦 然后等bark通知去app付款就行了？![image](https://user-images.githubusercontent.com/52702777/163720025-93f49e71-2d76-4fbd-8e65-d60950132e59.jpeg)

对的
