### ISSUE TITLE
运行完没有进入下一步

### ISSUE THREAD

**Issue by gusky6** [robGoods/sams#29]
之前版本运行没有问题
本次运行显示
Usage of C:\Users\gu\AppData\Local\Temp\go-build3597695511\b001\exe\main.exe:
 -deliveryType int
        可选，1 急速达，2， 全程配送 (default 2)
  -deviceId string
        可选，HTTP头部device-id
  -floorId int
        可选，1,普通商品 2,全球购保税 3,特殊订购自提 4,大件商品 5,厂家直供商品 6,特殊订购商品 7,失效商品 (default 1)
  -help
        show help
  -latitude string
        可选，HTTP头部latitude
  -longitude string
        可选，HTTP头部longitude
  -promotionId string
        可选，优惠券id
  -trackInfo string
        可选，HTTP头部track-info
等信息后
然后程序就没有进入下一步

**Comment by iscod** [comment]
> (default 2)
> -deviceId string
> 可选，HTTP头部device-id
> -floorId int
> 可选，1,普通商品 2,全球购保税 3,特殊订购自提 4,大件商品 5,厂家直供商品 6,特殊订购商品 7,失效商品 (default 1)
> -help
> show help
> -latitude string
> 可选，HTTP头部latitude
> -longitude string
> 可选，HTTP头部longitude
> -promotionId string

运行命令发下，你这是最新代码吗？commit是多少？

**Comment by gusky6** [comment]
![1](https://user-images.githubusercontent.com/103904381/163772837-8b635670-9802-4196-b823-0be4a59fbc49.PNG)
按照go run main.go --authToken=xxx 运行后，没有修改main.go

**Comment by gusky6** [comment]
![2](https://user-images.githubusercontent.com/103904381/163774226-1d5280e4-c4a6-4f4f-b592-6a8515df05cd.PNG)
对go不熟悉

**Comment by gusky6** [comment]
![3](https://user-images.githubusercontent.com/103904381/163775280-3addcdd3-43dc-45cf-b854-48a8d2922228.PNG)

**Comment by gusky6** [comment]
flag provided but not defined: -authToken
Usage of C:\Users\gu\AppData\Local\Temp\go-build210799902\b001\exe\main.exe:
运行后temp文件里没有生成go-build210799902文件

**Comment by iscod** [comment]
> 件里没有生成go-build210799902文

你这个看起来不是最新代码，先更新一下，最新版本是可以使用优惠券的

**Comment by gusky6** [comment]
更新了，可以运行，感谢！
