### ISSUE TITLE
安卓HttpCanary启动后山姆APP无法登录

### ISSUE THREAD

**Issue by hywu091** [robGoods/sams#3]
RT，安卓手机HttpCanary抓包启动后Chrome可以正常访问站点，但山姆APP无法登录的问题

**Comment by hywu091** [comment]
> RT，安卓手机HttpCanary抓包启动后Chrome可以正常访问站点，但山姆APP无法登录的问题

**Comment by hywu091** [comment]
电脑端Charles抓微信小程序的包，如果开启SSL Proxy同样无法访问山姆小程序

**Comment by iscod** [comment]
http能抓到吗？charles抓包https需要设置证书，你设置没有？

**Comment by hywu091** [comment]
已解决，正确配置Charles证书后可抓到。感谢。

**Comment by peng530** [comment]
> 

我也遇到类似的问题，请问怎么正确配置证书？
