### ISSUE TITLE
安装GO环境后运行会提示连接超时（1.8版本）

### ISSUE THREAD

**Issue by shutdown3971** [robGoods/sams#30]
请帮忙看下，是我设置问题吗？感谢。

C:\Users\lin\Downloads\Compressed\sams-master\sams-master>go run main.go --authToken=
go: github.com/tidwall/gjson@v1.14.0: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod": dial tcp 172.217.163.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
go: downloading github.com/tidwall/gjson v1.14.0
go: github.com/tidwall/gjson@v1.14.0: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod": dial tcp 172.217.163.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by iscod** [comment]
> 请帮忙看下，是我设置问题吗？感谢。
> 
> C:\Users\lin\Downloads\Compressed\sams-master\sams-master>go run main.go --authToken= go: github.com/tidwall/gjson@v1.14.0: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod": dial tcp 172.217.163.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. go: downloading github.com/tidwall/gjson v1.14.0 go: github.com/tidwall/gjson@v1.14.0: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod": dial tcp 172.217.163.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

看下 #5

**Comment by shutdown3971** [comment]
> 

好的，我试试。

**Comment by shutdown3971** [comment]
> 



> > 请帮忙看下，是我设置的问题吗？谢谢。
> > C:\Users\lin\Downloads\Compressed\sams-master\sams-master>go run main.go --authToken= go: github.com/tidwall/gjson@v1.14.0: Get " [https://proxy. golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod](https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod) ": dial tcp 172.217.163.49:443: connectex: 连接尝试失败，因为连接方在一段时间后没有正确响应，或建立连接失败，因为连接的主机没有响应。go: 下载 github.com/tidwall/gjson v1.14.0 go: github.com/tidwall/gjson@v1.14.0: 获取" [https://proxy.golang.org/github.com/tidwall/gjson/@v/ v1.14.0.mod](https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod)": dial tcp 172.217.163.49:443: connectex: 连接尝试失败，因为连接方在一段时间后没有正确响应，或者连接失败，因为连接的主机没有响应。
> 
> 看下#5和你的问题一样

哇！！！感谢你的，它神奇的跑起来了！！
