### ISSUE TITLE
楼层ID不合法

### ISSUE THREAD

**Issue by mnbvcxz8** [robGoods/sams#33]
########## 提交订单中【17:15:26】 ###########
下单失败：楼层ID不合法

今天提交订单时候，提示楼层ID不合法，我看了commitpay.go ：
	FloorId:            0,                   //急速时选1
是不是sam把这个默认值改掉了？

**Comment by maybeqwe** [comment]
同样遇到了这个问题，请问应该怎么解决呢？快断粮了0.0

**Comment by iscod** [comment]
> ########## 提交订单中【17:15:26】 ########### 下单失败：楼层ID不合法
> 
> 今天提交订单时候，提示楼层ID不合法，我看了commitpay.go ： FloorId: 0, //急速时选1 是不是sam把这个默认值改掉了？

app测试floorId是1，等我更新下

**Comment by iscod** [comment]
> 同样遇到了这个问题，请问应该怎么解决呢？快断粮了0.0

改成“1”试下

**Comment by mnbvcxz8** [comment]
1 应该是极速达，会提示 送达日期不能为空

**Comment by maybeqwe** [comment]
> > 同样遇到了这个问题，请问应该怎么解决呢？快断粮了0.0
> 
> 改成“1”试下
会提示:下单失败：收货时间为空

**Comment by gusky6** [comment]
遇到同样的问题

**Comment by iscod** [comment]
> 1 应该是极速达，会提示 送达日期不能为空

下的其它地区的全城配送也是1

**Comment by NeverArgueWithGF** [comment]
> > 1 应该是极速达，会提示 送达日期不能为空
> 
> 下的其它地区的全城配送也是1

改成1会提示收获时间为空

**Comment by mnbvcxz8** [comment]
可否把session.SettleDeliveryInfo.ExpectArrivalEndTime = "" 给一个比较大的时间范围，比如给 5月30日

**Comment by iscod** [comment]
> 可否把session.SettleDeliveryInfo.ExpectArrivalEndTime = "" 给一个比较大的时间范围，比如给 5月30日

之前测试不能随便给，会检验时间

**Comment by mnbvcxz8** [comment]
> 
那有可能是sam修正这个bug了。
不过之前floorid 为0 是可以下单的，会不会是把支付方式的0和1合并了，极速达和全城配都合并为1了。

**Comment by gusky6** [comment]
修改了前面的问题，但是下单时间为空

**Comment by mnbvcxz8** [comment]
我把为空的日期改成了 session.SettleDeliveryInfo.ExpectArrivalEndTime = v.EndRealTime
把pay里面的floorid 设置为1
从log看起来配送时段是可以用的，但是在提交订单的CommitPay环节，它重新加了配送时间的校验 @iscod 

########## 获取当前可用配送时间【18:57:05】 ###########
配送时间： 2022/04/19 周二 09:00 - 15:00, 是否可用：false
发现可用的配送时段::2022/04/19 周二 09:00 - 15:00!
########## 提交订单中【18:57:06】 ###########
下单失败：当前配送时间段已约满，请重新选择配送时段

**Comment by maybeqwe** [comment]
> 我把为空的日期改成了 session.SettleDeliveryInfo.ExpectArrivalEndTime = v.EndRealTime 把pay里面的floorid 设置为1 从log看起来配送时段是可以用的，但是在提交订单的CommitPay环节，它重新加了配送时间的校验 @iscod
> 
> ########## 获取当前可用配送时间【18:57:05】 ########### 配送时间： 2022/04/19 周二 09:00 - 15:00, 是否可用：false 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【18:57:06】 ########### 下单失败：当前配送时间段已约满，请重新选择配送时段

我尝试了你说的方法，错误也是和你一样

**Comment by mnbvcxz8** [comment]
case "NOT_DELIVERY_CAPACITY_ERROR":
			return NotDeliverCapCityErr
@iscod 原来的api里面也有重新验证配送时间，我前面说的不对。

看来只是把送货日期为空这个改过了，有办法获取送货日期list么？或者按照这种格式 做个loop（2022/04/19 周二 09:00 - 15:00），一直往下尝试，
比如
2022/04/19 周二 09:00 - 15:00
2022/04/19 周二 15:00 - 21:00
2022/04/20 周二 09:00 - 15:00
2022/04/20 周二 15:00 - 21:00
2022/04/21 周二 09:00 - 15:00
2022/04/21 周二 15:00 - 21:00
....

**Comment by iscod** [comment]
应该是sam’s修正了这问题，你用的是hack版本吧？hack版本就是使用的空字符跳过验证

**Comment by mnbvcxz8** [comment]
> 应该是sam’s修正了这问题，你用的是hack版本吧？hack版本就是使用的空字符跳过验证

是的，那为什么会现在跳出错误：送货时间不能为空呢？

**Comment by iscod** [comment]
> > 应该是sam’s修正了这问题，你用的是hack版本吧？hack版本就是使用的空字符跳过验证
> 
> 是的，那为什么会现在跳出错误：送货时间不能为空呢？



> ```
> 	case "NOT_DELIVERY_CAPACITY_ERROR":
> 		return NotDeliverCapCityErr
> ```
> 
> 
>      
>   
> 
> @iscod 原来的api里面也有重新验证配送时间，我前面说的不对。
> 
> 
> 看来只是把送货日期为空这个改过了，有办法获取送货日期list么？或者按照这种格式 做个loop（2022/04/19 周二 09:00 - 15:00），一直往下尝试，
> 比如
> 2022/04/19 周二 09:00 - 15:00
> 2022/04/19 周二 15:00 - 21:00
> 2022/04/20 周二 09:00 - 15:00
> 2022/04/20 周二 15:00 - 21:00
> 2022/04/21 周二 09:00 - 15:00
> 2022/04/21 周二 15:00 - 21:00
> ....

有获取送货时间的list，这个是山姆的接口

**Comment by mnbvcxz8** [comment]
> 应该是sam’s修正了这问题，你用的是hack版本吧？hack版本就是使用的空字符跳过验证

能否用我上面说的那个列表逐个尝试的方式处理呢

**Comment by mnbvcxz8** [comment]
> > > 应该是sam’s修正了这问题，你用的是hack版本吧？hack版本就是使用的空字符跳过验证
> > 
> > 
> > 是的，那为什么会现在跳出错误：送货时间不能为空呢？
> 
> > ```
> > 	case "NOT_DELIVERY_CAPACITY_ERROR":
> > 		return NotDeliverCapCityErr
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @iscod 原来的api里面也有重新验证配送时间，我前面说的不对。
> > 看来只是把送货日期为空这个改过了，有办法获取送货日期list么？或者按照这种格式 做个loop（2022/04/19 周二 09:00 - 15:00），一直往下尝试，
> > 比如
> > 2022/04/19 周二 09:00 - 15:00
> > 2022/04/19 周二 15:00 - 21:00
> > 2022/04/20 周二 09:00 - 15:00
> > 2022/04/20 周二 15:00 - 21:00
> > 2022/04/21 周二 09:00 - 15:00
> > 2022/04/21 周二 15:00 - 21:00
> > ....
> 
> 有获取送货时间的list，这个是山姆的接口

我的想法是，是否可以按照它原来列表的值逐一去尝试，不直接从它的列表获取值

**Comment by iscod** [comment]
> > 应该是sam’s修正了这问题，你用的是hack版本吧？hack版本就是使用的空字符跳过验证
> 
> 是的，那为什么会现在跳出错误：送货时间不能为空呢？

hack版本就是设置的空字符，没加收货时间的

**Comment by iscod** [comment]
> > > > 应该是sam’s修正了这问题，你用的是hack版本吧？hack版本就是使用的空字符跳过验证
> > > 
> > > 
> > > 是的，那为什么会现在跳出错误：送货时间不能为空呢？
> > 
> > 
> > > ```
> > > 	case "NOT_DELIVERY_CAPACITY_ERROR":
> > > 		return NotDeliverCapCityErr
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @iscod 原来的api里面也有重新验证配送时间，我前面说的不对。
> > > 看来只是把送货日期为空这个改过了，有办法获取送货日期list么？或者按照这种格式 做个loop（2022/04/19 周二 09:00 - 15:00），一直往下尝试，
> > > 比如
> > > 2022/04/19 周二 09:00 - 15:00
> > > 2022/04/19 周二 15:00 - 21:00
> > > 2022/04/20 周二 09:00 - 15:00
> > > 2022/04/20 周二 15:00 - 21:00
> > > 2022/04/21 周二 09:00 - 15:00
> > > 2022/04/21 周二 15:00 - 21:00
> > > ....
> > 
> > 
> > 有获取送货时间的list，这个是山姆的接口
> 
> 我的想法是，是否可以按照它原来列表的值逐一去尝试，不直接从它的列表获取值

没试过，等会试试，每个时间段都有开启和结束时间，不确定能否可行

**Comment by mnbvcxz8** [comment]
比如
session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"

我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写

**Comment by mnbvcxz8** [comment]
> > > > > 应该是sam’s修正了这问题，你用的是hack版本吧？hack版本就是使用的空字符跳过验证
> > > > 
> > > > 
> > > > 是的，那为什么会现在跳出错误：送货时间不能为空呢？
> > > 
> > > 
> > > > ```
> > > > 	case "NOT_DELIVERY_CAPACITY_ERROR":
> > > > 		return NotDeliverCapCityErr
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > @iscod 原来的api里面也有重新验证配送时间，我前面说的不对。
> > > > 看来只是把送货日期为空这个改过了，有办法获取送货日期list么？或者按照这种格式 做个loop（2022/04/19 周二 09:00 - 15:00），一直往下尝试，
> > > > 比如
> > > > 2022/04/19 周二 09:00 - 15:00
> > > > 2022/04/19 周二 15:00 - 21:00
> > > > 2022/04/20 周二 09:00 - 15:00
> > > > 2022/04/20 周二 15:00 - 21:00
> > > > 2022/04/21 周二 09:00 - 15:00
> > > > 2022/04/21 周二 15:00 - 21:00
> > > > ....
> > > 
> > > 
> > > 有获取送货时间的list，这个是山姆的接口
> > 
> > 
> > 我的想法是，是否可以按照它原来列表的值逐一去尝试，不直接从它的列表获取值
> 
> 没试过，等会试试，每个时间段都有开启和结束时间，不确定能否可行

我看到他就这两段时间

**Comment by iscod** [comment]
> 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> 
> 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写

这是个时间戳，直接填成时间戳。注意是毫秒

**Comment by iscod** [comment]
> > 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> > 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写
> 
> 这是个时间戳，直接填成时间戳。注意是毫秒

ExpectArrivalEndTime是结束的时间，ExpectArrivalTime是开始的时间戳

**Comment by maybeqwe** [comment]
> > > 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> > > 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写
> > 
> > 
> > 这是个时间戳，直接填成时间戳。注意是毫秒
> 
> ExpectArrivalEndTime是结束的时间，ExpectArrivalTime是开始的时间戳

坐等大佬更新新版本带我抢菜   555

**Comment by mnbvcxz8** [comment]
> > > 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> > > 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写
> > 
> > 
> > 这是个时间戳，直接填成时间戳。注意是毫秒
> 
> ExpectArrivalEndTime是结束的时间，ExpectArrivalTime是开始的时间戳

					session.SettleDeliveryInfo.ExpectArrivalTime = "2022/04/20 15:00"
					session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/20 21:00"

格式不对，改咋写，求教

**Comment by huzisir** [comment]
hack版本修复了吗，我也提示这个

**Comment by iscod** [comment]
> hack版本修复了吗，我也提示这个

还没

**Comment by huzisir** [comment]
感觉hack版本更快一点，坐等大佬修复

**Comment by mnbvcxz8** [comment]
> > > > 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> > > > 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写
> > > 
> > > 
> > > 这是个时间戳，直接填成时间戳。注意是毫秒
> > 
> > 
> > ExpectArrivalEndTime是结束的时间，ExpectArrivalTime是开始的时间戳
> 
> ```
> 				session.SettleDeliveryInfo.ExpectArrivalTime = "2022/04/20 15:00"
> 				session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/20 21:00"
> ```
> 
> 格式不对，改咋写，求教
> 
> 用这个https://tool.lu/timestamp 转换一下换成时间戳

很奇怪，第一段是我用v.StartRealTime 和v.EndRealTime来赋值。
第二段是用时间戳的方式 赋予同样的值，但得到的错误信息是不同的。

发现可用的配送时段::2022/04/19 周二 09:00 - 15:00!
########## 提交订单中【20:28:20】 ###########
下单失败：当前配送时间段已约满，请重新选择配送时段


发现可用的配送时段::2022/04/19 周二 09:00 - 15:00!
########## 提交订单中【20:26:36】 ###########
下单失败：扣减运力失败

**Comment by huzisir** [comment]
> > > > > 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> > > > > 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写
> > > > 
> > > > 
> > > > 这是个时间戳，直接填成时间戳。注意是毫秒
> > > 
> > > 
> > > ExpectArrivalEndTime是结束的时间，ExpectArrivalTime是开始的时间戳
> > 
> > 
> > ```
> > 				session.SettleDeliveryInfo.ExpectArrivalTime = "2022/04/20 15:00"
> > 				session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/20 21:00"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 格式不对，改咋写，求教
> > 用这个https://tool.lu/timestamp 转换一下换成时间戳
> 
> 很奇怪，第一段是我用v.StartRealTime 和v.EndRealTime来赋值。 第二段是用时间戳的方式 赋予同样的值，但得到的错误信息是不同的。
> 
> 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:28:20】 ########### 下单失败：当前配送时间段已约满，请重新选择配送时段
> 
> 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:26:36】 ########### 下单失败：扣减运力失败

这样的提示不是正常的吗，因为还没到9点没放运力

**Comment by mnbvcxz8** [comment]
> > > > > > 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> > > > > > 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写
> > > > > 
> > > > > 
> > > > > 这是个时间戳，直接填成时间戳。注意是毫秒
> > > > 
> > > > 
> > > > ExpectArrivalEndTime是结束的时间，ExpectArrivalTime是开始的时间戳
> > > 
> > > 
> > > ```
> > > 				session.SettleDeliveryInfo.ExpectArrivalTime = "2022/04/20 15:00"
> > > 				session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/20 21:00"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 格式不对，改咋写，求教
> > > 用这个https://tool.lu/timestamp 转换一下换成时间戳
> > 
> > 
> > 很奇怪，第一段是我用v.StartRealTime 和v.EndRealTime来赋值。 第二段是用时间戳的方式 赋予同样的值，但得到的错误信息是不同的。
> > 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:28:20】 ########### 下单失败：当前配送时间段已约满，请重新选择配送时段
> > 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:26:36】 ########### 下单失败：扣减运力失败
> 
> 这样的提示不是正常的吗，因为还没到9点没放运力

看到错误信息不同没

**Comment by iscod** [comment]
> 

9:00 - 15:00? 不是 18：00吗？我测试的两种方式一样，都是提示“当前配送时间段已约满，请重新选择配送时段”

**Comment by mnbvcxz8** [comment]
> 9:00 - 15:00? 不是 18：00吗？我测试的两种方式一样，都是提示“当前配送时间段已约满，请重新选择配送时段”

为啥我看到的都是提示这两个时间段，所以我就按照这两个时间段赋值了。
你试试把时间设为2022/4/25 呢，时间远一点看看还会提示约满

配送时间： 2022/04/19 周二 09:00 - 15:00, 是否可用：false
配送时间： 2022/04/19 周二 15:00 - 21:00, 是否可用：false

**Comment by iscod** [comment]
> > > > > 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> > > > > 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写
> > > > 
> > > > 
> > > > 这是个时间戳，直接填成时间戳。注意是毫秒
> > > 
> > > 
> > > ExpectArrivalEndTime是结束的时间，ExpectArrivalTime是开始的时间戳
> > 
> > 
> > ```
> > 				session.SettleDeliveryInfo.ExpectArrivalTime = "2022/04/20 15:00"
> > 				session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/20 21:00"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 格式不对，改咋写，求教
> > 用这个https://tool.lu/timestamp 转换一下换成时间戳
> 
> 很奇怪，第一段是我用v.StartRealTime 和v.EndRealTime来赋值。 第二段是用时间戳的方式 赋予同样的值，但得到的错误信息是不同的。
> 
> 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:28:20】 ########### 下单失败：当前配送时间段已约满，请重新选择配送时段
> 
> 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:26:36】 ########### 下单失败：扣减运力失败

扣减运力失败应该是你传的时间戳不对，是毫秒，不是秒，
```
 "expectArrivalTime": "1650330000000"//2022-04-19 09:00:00
"expectArrivalEndTime": "1650362400000"//2022-04-19 18:00:00
```

**Comment by maybeqwe** [comment]
> > 9:00 - 15:00? 不是 18：00吗？我测试的两种方式一样，都是提示“当前配送时间段已约满，请重新选择配送时段”
> 
> 为啥我看到的都是提示这两个时间段，所以我就按照这两个时间段赋值了。 你试试把时间设为2022/4/25 呢，时间远一点看看还会提示约满
> 
> 配送时间： 2022/04/19 周二 09:00 - 15:00, 是否可用：false 配送时间： 2022/04/19 周二 15:00 - 21:00, 是否可用：false



> > > > > 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> > > > > 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写
> > > > 
> > > > 
> > > > 这是个时间戳，直接填成时间戳。注意是毫秒
> > > 
> > > 
> > > ExpectArrivalEndTime是结束的时间，ExpectArrivalTime是开始的时间戳
> > 
> > 
> > ```
> > 				session.SettleDeliveryInfo.ExpectArrivalTime = "2022/04/20 15:00"
> > 				session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/20 21:00"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 格式不对，改咋写，求教
> > 用这个https://tool.lu/timestamp 转换一下换成时间戳
> 
> 很奇怪，第一段是我用v.StartRealTime 和v.EndRealTime来赋值。 第二段是用时间戳的方式 赋予同样的值，但得到的错误信息是不同的。
> 
> 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:28:20】 ########### 下单失败：当前配送时间段已约满，请重新选择配送时段
> 
> 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:26:36】 ########### 下单失败：扣减运力失败

请问有成功吗?

**Comment by iscod** [comment]
重磅信息，hack版本更新！！！

**Comment by mnbvcxz8** [comment]
> > > 9:00 - 15:00? 不是 18：00吗？我测试的两种方式一样，都是提示“当前配送时间段已约满，请重新选择配送时段”
> > 
> > 
> > 为啥我看到的都是提示这两个时间段，所以我就按照这两个时间段赋值了。 你试试把时间设为2022/4/25 呢，时间远一点看看还会提示约满
> > 配送时间： 2022/04/19 周二 09:00 - 15:00, 是否可用：false 配送时间： 2022/04/19 周二 15:00 - 21:00, 是否可用：false
> 
> > > > > > 比如 session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/19 周二 09:00 - 15:00"
> > > > > > 我不会写go，可以尝试把值改为19号的时间段，这个日期应该怎么写
> > > > > 
> > > > > 
> > > > > 这是个时间戳，直接填成时间戳。注意是毫秒
> > > > 
> > > > 
> > > > ExpectArrivalEndTime是结束的时间，ExpectArrivalTime是开始的时间戳
> > > 
> > > 
> > > ```
> > > 				session.SettleDeliveryInfo.ExpectArrivalTime = "2022/04/20 15:00"
> > > 				session.SettleDeliveryInfo.ExpectArrivalEndTime = "2022/04/20 21:00"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 格式不对，改咋写，求教
> > > 用这个https://tool.lu/timestamp 转换一下换成时间戳
> > 
> > 
> > 很奇怪，第一段是我用v.StartRealTime 和v.EndRealTime来赋值。 第二段是用时间戳的方式 赋予同样的值，但得到的错误信息是不同的。
> > 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:28:20】 ########### 下单失败：当前配送时间段已约满，请重新选择配送时段
> > 发现可用的配送时段::2022/04/19 周二 09:00 - 15:00! ########## 提交订单中【20:26:36】 ########### 下单失败：扣减运力失败
> 
> 请问有成功吗?

没有

**Comment by mnbvcxz8** [comment]
> 重磅信息，hack版本更新！！！

棒棒的！

**Comment by iscod** [comment]
> > 重磅信息，hack版本更新！！！
> 
> 棒棒的！

可以看下哪些不同，只是临时解决方案

**Comment by NeverArgueWithGF** [comment]
还是下单失败 提示运力扣减失败

**Comment by mnbvcxz8** [comment]
> > > 重磅信息，hack版本更新！！！
> > 
> > 
> > 棒棒的！
> 
> 可以看下哪些不同，只是临时解决方案

@iscod 大神， 还是一样的错误

**Comment by shifanhu** [comment]
> > > > 重磅信息，hack版本更新！！！
> > > 
> > > 
> > > 棒棒的！
> > 
> > 
> > 可以看下哪些不同，只是临时解决方案
> 
> @iscod 大神， 还是一样的错误

我试了一下我可以了

**Comment by mnbvcxz8** [comment]
> > > > > 重磅信息，hack版本更新！！！
> > > > 
> > > > 
> > > > 棒棒的！
> > > 
> > > 
> > > 可以看下哪些不同，只是临时解决方案
> > 
> > 
> > @iscod 大神， 还是一样的错误
> 
> 我试了一下我可以了

我还是不行，你是一次成功，完全没有报错么

**Comment by shifanhu** [comment]
> > > > > > 重磅信息，hack版本更新！！！
> > > > > 
> > > > > 
> > > > > 棒棒的！
> > > > 
> > > > 
> > > > 可以看下哪些不同，只是临时解决方案
> > > 
> > > 
> > > @iscod 大神， 还是一样的错误
> > 
> > 
> > 我试了一下我可以了
> 
> 我还是不行，你是一次成功，完全没有报错么

是的 你有下最新的code吗

**Comment by mnbvcxz8** [comment]
有啊，刚下载的最新的hack

**Comment by NeverArgueWithGF** [comment]
> > > > > > > 重磅信息，hack版本更新！！！
> > > > > > 
> > > > > > 
> > > > > > 棒棒的！
> > > > > 
> > > > > 
> > > > > 可以看下哪些不同，只是临时解决方案
> > > > 
> > > > 
> > > > @iscod 大神， 还是一样的错误
> > > 
> > > 
> > > 我试了一下我可以了
> > 
> > 
> > 我还是不行，你是一次成功，完全没有报错么
> 
> 是的 你有下最新的code吗

我这边也不行 提示运力扣减失败

**Comment by huzisir** [comment]
大佬啊，感谢

**Comment by likang7** [comment]
> 

StoreDeliveryTemplateId 这个id是啥，感觉不会配送吧。。

**Comment by likang7** [comment]
> StoreDeliveryTemplateId 这个id是啥，感觉不会配送吧。。

StoreDeliveryTemplateId 这个id是啥，是不是其他城市的，感觉不会配送吧

**Comment by likang7** [comment]
> > > 重磅信息，hack版本更新！！！
> > 
> > 
> > 棒棒的！
> 
> 可以看下哪些不同，只是临时解决方案

StoreDeliveryTemplateId 这个id是啥，是不是其他城市的，感觉不会配送吧

**Comment by iscod** [comment]
> > > > 重磅信息，hack版本更新！！！
> > > 
> > > 
> > > 棒棒的！
> > 
> > 
> > 可以看下哪些不同，只是临时解决方案
> 
> StoreDeliveryTemplateId 这个id是啥，是不是其他城市的，感觉不会配送吧

其它城市的

**Comment by NeverArgueWithGF** [comment]
麻烦问下 为什么还是提示运力扣减失败呀。。

**Comment by mnbvcxz8** [comment]
> > > > > 重磅信息，hack版本更新！！！
> > > > 
> > > > 
> > > > 棒棒的！
> > > 
> > > 
> > > 可以看下哪些不同，只是临时解决方案
> > 
> > 
> > StoreDeliveryTemplateId 这个id是啥，是不是其他城市的，感觉不会配送吧
> 
> 其它城市的

我还是同样的错误，要做什么操作么

**Comment by iscod** [comment]
> 麻烦问下 为什么还是提示运力扣减失败呀。。

目前不清楚原因，可以尝试下换个id

**Comment by NeverArgueWithGF** [comment]
> StoreDeliveryTemplateId



> > 麻烦问下 为什么还是提示运力扣减失败呀。。
> 
> 目前不清楚原因，可以尝试下换个id

换这个deliveryTemplateId吗

**Comment by mnbvcxz8** [comment]
> > 麻烦问下 为什么还是提示运力扣减失败呀。。
> 
> 目前不清楚原因，可以尝试下换个id

换了token，也换了网络，都不行。再换就只能换电脑了

**Comment by iscod** [comment]
> > > 麻烦问下 为什么还是提示运力扣减失败呀。。
> > 
> > 
> > 目前不清楚原因，可以尝试下换个id
> 
> 换了token，也换了网络，都不行。再换就只能换电脑了

😅😅😅跟这些都没关系。。。。

**Comment by mnbvcxz8** [comment]
> > > > 麻烦问下 为什么还是提示运力扣减失败呀。。
> > > 
> > > 
> > > 目前不清楚原因，可以尝试下换个id
> > 
> > 
> > 换了token，也换了网络，都不行。再换就只能换电脑了
> 
> 😅😅😅跟这些都没关系。。。。

那换哪个ID？ :$

**Comment by iscod** [comment]
> > > > > 麻烦问下 为什么还是提示运力扣减失败呀。。
> > > > 
> > > > 
> > > > 目前不清楚原因，可以尝试下换个id
> > > 
> > > 
> > > 换了token，也换了网络，都不行。再换就只能换电脑了
> > 
> > 
> > 😅😅😅跟这些都没关系。。。。
> 
> 那换哪个ID？ :$

StoreDeliveryTemplateId这个啊

**Comment by mnbvcxz8** [comment]
你有别的ID么？我试试

**Comment by iscod** [comment]
> 你有别的ID么？我试试

你地址添加个其它城市，下个全城配送的单，抓包看下。我不方便现在

**Comment by NeverArgueWithGF** [comment]
> 



> > 你有别的ID么？我试试
> 
> 你地址添加个其它城市，下个全城配送的单，抓包看下。我不方便现在

请问这个deliveryTemplateId是在哪个方法里面呀

**Comment by iscod** [comment]
> > 
> 
> > > 你有别的ID么？我试试
> > 
> > 
> > 你地址添加个其它城市，下个全城配送的单，抓包看下。我不方便现在
> 
> 请问这个deliveryTemplateId是在哪个方法里面呀

commitPay里面

**Comment by NeverArgueWithGF** [comment]
> > > 
> > 
> > 
> > > > 你有别的ID么？我试试
> > > 
> > > 
> > > 你地址添加个其它城市，下个全城配送的单，抓包看下。我不方便现在
> > 
> > 
> > 请问这个deliveryTemplateId是在哪个方法里面呀
> 
> commitPay里面

麻烦问下您地址对应的配送门店是上海浦东店吗还是哪个店？

**Comment by NeverArgueWithGF** [comment]
> > > 
> > 
> > 
> > > > 你有别的ID么？我试试
> > > 
> > > 
> > > 你地址添加个其它城市，下个全城配送的单，抓包看下。我不方便现在
> > 
> > 
> > 请问这个deliveryTemplateId是在哪个方法里面呀
> 
> commitPay里面

麻烦问下557768328832252438这个值您是取得哪个店的deliveryid

**Comment by iscod** [comment]
> > > > > 你有别的ID么？我试试
> > > > 
> > > > 
> > > > 你地址添加个其它城市，下个全城配送的单，抓包看下。我不方便现在
> > > 
> > > 
> > > 请问这个deliveryTemplateId是在哪个方法里面呀
> > 
> > 
> > commitPay里面
> 
> 麻烦问下557768328832252438这个值您是取得哪个店的deliveryid

沈阳

**Comment by NeverArgueWithGF** [comment]
> > > > > > 你有别的ID么？我试试
> > > > > 
> > > > > 
> > > > > 你地址添加个其它城市，下个全城配送的单，抓包看下。我不方便现在
> > > > 
> > > > 
> > > > 请问这个deliveryTemplateId是在哪个方法里面呀
> > > 
> > > 
> > > commitPay里面
> > 
> > 
> > 麻烦问下557768328832252438这个值您是取得哪个店的deliveryid
> 
> 沈阳

还有些问题请教 发您邮箱了

**Comment by NeverArgueWithGF** [comment]
> > > > > > 你有别的ID么？我试试
> > > > > 
> > > > > 
> > > > > 你地址添加个其它城市，下个全城配送的单，抓包看下。我不方便现在
> > > > 
> > > > 
> > > > 请问这个deliveryTemplateId是在哪个方法里面呀
> > > 
> > > 
> > > commitPay里面
> > 
> > 
> > 麻烦问下557768328832252438这个值您是取得哪个店的deliveryid
> 
> 沈阳

为什么沈阳店的delivery ID可以下上海浦东店配送的单子？我试了用北京店的就不行。您这个是如何试出来的呢？

**Comment by iscod** [comment]
> 

不清楚啊，就换了换试下

**Comment by 2dot4** [comment]
> > > > > > > 你有别的ID么？我试试
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 你地址添加个其它城市，下个全城配送的单，抓包看下。我不方便现在
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 请问这个deliveryTemplateId是在哪个方法里面呀
> 
> > > > 
> 
> > > > 
> 
> > > > commitPay里面
> 
> > > 
> 
> > > 
> 
> > > 麻烦问下557768328832252438这个值您是取得哪个店的deliveryid
> 
> > 
> 
> > 沈阳
> 
> 
> 
> 为什么沈阳店的delivery ID可以下上海浦东店配送的单子？我试了用北京店的就不行。您这个是如何试出来的呢？

请问可以了吗？怎么设置呢。我还是存在问题，获取履约信息失败

**Comment by iscod** [comment]
> 

还没改

**Comment by NeverArgueWithGF** [comment]
> > 
> 
> 不清楚啊，就换了换试下

是找的有可配送时间的店取得吗 然后一个个试验的是吗

**Comment by iscod** [comment]
> 

对

**Comment by NeverArgueWithGF** [comment]
> > 
> 
> 对

有获取全国门店信息的接口嘛

**Comment by iscod** [comment]
> 

好像没有，没见到

**Comment by NeverArgueWithGF** [comment]
> > 
> 
> 好像没有，没见到

那就是一个一个改地址去抓的是吗

**Comment by XobilePidor** [comment]
@iscod 大佬，hack还会更新吗？

**Comment by iscod** [comment]
> @iscod 大佬，hack还会更新吗？

基本不会。没什么希望
