### ISSUE TITLE
有人知道何时释放运力么？几点执行脚本成功率高？

### ISSUE THREAD

**Issue by jifuwei** [robGoods/sams#35]

**Comment by iscod** [comment]
> _No description provided._

晚上8：40多其实就慢慢释放运力了

**Comment by jifuwei** [comment]
晚上21点后提示floorId不存在，然后运力天数就变成第二天了，是不是就抢不到了？

**Comment by robinspt** [comment]
> > _No description provided._
> 
> 晚上8：40多其实就慢慢释放运力了

8:40开始就一直运行吗？持续运行不知道会不会黑号？我现在都是开一会关一会

**Comment by meimxn** [comment]
这两天连续开了48小时，没有可用时段，捡不到漏，21点也没有

**Comment by meimxn** [comment]
这两天连续开了48小时，没有可用时段，捡不到漏，21点也没有。
不知道有没有成功下单的朋友。

**Comment by Jessie0914** [comment]
今天有抢成的老哥吗…山姆抢菜咋这么难。。

**Comment by zhuxl** [comment]
运送时间跳了，但是一直无可用配送时间段。。。

**Comment by tanjingyuan** [comment]
还想问问各位老哥，这个怎么使用啊。。。如何拿到token

**Comment by iscod** [comment]
> 还想问问各位老哥，这个怎么使用啊。。。如何拿到token

山姆app抓包, http头部有token

**Comment by iscod** [comment]
最新开放时间统计

1. 早上八点，开放极速达，脚本可以设置在7点50就开始。
2. 中午14点，开放全城配，脚本在14点前开始即可。该时间段基本都可以抢到
3. 这两个时间段都不是整点开始的，可能要延后几分钟到十几分钟后台在真正开放库存和运力。所有提前一会，多跑一会。

**Comment by SnoopyGo** [comment]
> 最新开放时间统计
> 
> 1. 早上八点，开放极速达，脚本可以设置在7点50就开始。
> 2. 中午14点，开放全城配，脚本在14点前开始即可。该时间段基本都可以抢到
> 3. 这两个时间段都不是整点开始的，可能要延后几分钟到十几分钟后台才真正开放库存和运力。所有提前一会，多跑一会。

发现作者大哥真的是好耐心，有问必答，同时真的很感谢你们这些人，开源帮助了太多有需要的人，希望疫情结束了可以开放捐助，真的很谢谢你们！

**Comment by iscod** [comment]
> > 最新开放时间统计
> > 
> > 1. 早上八点，开放极速达，脚本可以设置在7点50就开始。
> > 2. 中午14点，开放全城配，脚本在14点前开始即可。该时间段基本都可以抢到
> > 3. 这两个时间段都不是整点开始的，可能要延后几分钟到十几分钟后台才真正开放库存和运力。所有提前一会，多跑一会。
> 
> 发现作者大哥真的是好耐心，有问必答，同时真的很感谢你们这些人，开源帮助了太多有需要的人，希望疫情结束了可以开放捐助，真的很谢谢你们！

我也是在家闲的🤣🤣

**Comment by SnoopyGo** [comment]
> 最新开放时间统计
> 
> 1. 早上八点，开放极速达，脚本可以设置在7点50就开始。
> 2. 中午14点，开放全城配，脚本在14点前开始即可。该时间段基本都可以抢到
> 3. 这两个时间段都不是整点开始的，可能要延后几分钟到十几分钟后台才真正开放库存和运力。所有提前一会，多跑一会。

解封了！！！作者大哥开一个donate，我意思意思下，感谢您的开源！😍😍😍

**Comment by iscod** [comment]
> > 最新开放时间统计
> > 
> > 1. 早上八点，开放极速达，脚本可以设置在7点50就开始。
> > 2. 中午14点，开放全城配，脚本在14点前开始即可。该时间段基本都可以抢到
> > 3. 这两个时间段都不是整点开始的，可能要延后几分钟到十几分钟后台才真正开放库存和运力。所有提前一会，多跑一会。
> 
> 解封了！！！作者大哥开一个donate，我意思意思下，感谢您的开源！😍😍😍

首页有，🙏🙏🙏🙏
