### ISSUE TITLE
今天是不是山姆后台更新了 为啥感觉今天很难抢啊

### ISSUE THREAD

**Issue by JONREAN2** [robGoods/sams#36]

**Comment by iscod** [comment]
> _No description provided._

山姆系统升级了

**Comment by maybeqwe** [comment]
> > _No description provided._
> 
> 山姆系统升级了

请问更新后的hack版扣减运力失败应该怎么办呢？

**Comment by JONREAN2** [comment]
> > _No description provided._
> 
> 山姆系统升级了

咋办啊 老哥 我们全靠你啦 明天会更新对吧

**Comment by 2dot4** [comment]
唉 今天完全抢不到咯😂

**Comment by shutdown3971** [comment]
emmm。。。。我就说今天怎么也抢不到呢

**Comment by shutdown3971** [comment]
emmm。。。。我就说今天怎么也抢不到呢，我看到脚本一直说是无可用配送时间
