### ISSUE TITLE
卡券促销id怎么得到

### ISSUE THREAD

**Issue by 2dot4** [robGoods/sams#39]
请问一下🫡

**Comment by Matata-lol** [comment]
确认订单抓包后可以看到，在getSettleInfo这个接口里面的couponList中。

**Comment by 2dot4** [comment]
> 确认订单抓包后可以看到，在getSettleInfo这个接口里面的couponList中。

请问是下面的哪个值呢，谢谢

"couponVO": {
        "templateId": "8GeAgH0SJ3NA%2BPo16EaD7GHnijoqb14cG8iEuzx5wzCYWDXPP%2FbuPkK8Dy1fOWSX",
        "code": "911190040679881057527",
        "name": "20元冷鲜肉券",
        "ruleId": "1162378069167442354",
        "nameEnglish": null,
        "sourceType": 1,
        "couponType": 1,
        "adaptProductType": 4,
        "subCouponType": null,
        "promotion": {
          "condition": {
            "value": "2100",
            "type": 1
          },
          "discount": {
            "value": "2000",
            "maxValue": null
          }

**Comment by Matata-lol** [comment]
ruleId

**Comment by Matata-lol** [comment]
选中以后看请求的body，不是看返回的

**Comment by 2dot4** [comment]
非常感谢

**Comment by iscod** [comment]
> > 确认订单抓包后可以看到，在getSettleInfo这个接口里面的couponList中。
> 
> 请问是下面的哪个值呢，谢谢
> 
> "couponVO": { "templateId": "8GeAgH0SJ3NA%2BPo16EaD7GHnijoqb14cG8iEuzx5wzCYWDXPP%2FbuPkK8Dy1fOWSX", "code": "911190040679881057527", "name": "20元冷鲜肉券", "ruleId": "1162378069167442354", "nameEnglish": null, "sourceType": 1, "couponType": 1, "adaptProductType": 4, "subCouponType": null, "promotion": { "condition": { "value": "2100", "type": 1 }, "discount": { "value": "2000", "maxValue": null }

ruleId": "1162378069167442354
