### ISSUE TITLE
运行时报错卡券促销ID不能为空

### ISSUE THREAD

**Issue by grbrust** [robGoods/sams#40]

**Comment by HUI2125281** [comment]
我也报这个错，不用优惠券不行么？

**Comment by gyf19** [comment]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/233857/163835533-1c1bdb13-1551-478c-966c-76cd380a06c7.png">
var promotionIds []string
	if *promotionId != "" {
		promotionIds = strings.Split(*promotionId, `,`)
	}

按上面改一下 @HUI2125281  @zyr3536 @grbrust

**Comment by poctopus** [comment]
还是下单失败。

**Comment by zhoubo518** [comment]
> 

可以了，但不能使用优惠券了，问题不大，谢谢啦！

**Comment by zyr3536** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/26672012/163842932-cade775a-7977-4371-a41a-253f895ab244.png">  @gyf19 我这么改了下

**Comment by iscod** [comment]
> <img alt="image" width="496" src="https://user-images.githubusercontent.com/26672012/163842932-cade775a-7977-4371-a41a-253f895ab244.png"> @gyf19 我这么改了下

提下pull

**Comment by iscod** [comment]
> <img alt="image" width="496" src="https://user-images.githubusercontent.com/26672012/163842932-cade775a-7977-4371-a41a-253f895ab244.png"> @gyf19 我这么改了下

默认空字符串，会切分成长度是1的切片。测试下，我现在不方便

**Comment by Matata-lol** [comment]
<img width="831" alt="Screen Shot 2022-04-19 at 4 17 18 AM" src="https://user-images.githubusercontent.com/2107817/163871250-cc6a7ff2-653b-4918-82c6-b3d581c3b7a3.png">
按照这个修改一下就可以了

**Comment by Matata-lol** [comment]
原因是提交订单的时候如果带了couponList就不能为空，如果不使用，不带这个字段就可以了。

**Comment by huzisir** [comment]
这个用goland修改吗，还是啥编译器

**Comment by maybeqwe** [comment]
> <img alt="image" width="577" src="https://user-images.githubusercontent.com/233857/163835533-1c1bdb13-1551-478c-966c-76cd380a06c7.png">
> 
> ` var promotionIds []string if *promotionId != "" { promotionIds = strings.Split(*promotionId,`,`) }
> 
> `
> 
> 按上面改一下 @HUI2125281 @zyr3536 @grbrust

还是不行，提示:下单失败：获取履约配送信息异常

**Comment by iscod** [comment]
> > <img alt="image" width="577" src="https://user-images.githubusercontent.com/233857/163835533-1c1bdb13-1551-478c-966c-76cd380a06c7.png">
> > ` var promotionIds []string if *promotionId != "" { promotionIds = strings.Split(*promotionId,`,`) }
> > `
> > 按上面改一下 @HUI2125281 @zyr3536 @grbrust
> 
> 还是不行，提示:下单失败：获取履约配送信息异常

履约配送信息和卡券没关系，这个我先close了
