### ISSUE TITLE
楼层ID不合法

### ISSUE THREAD

**Issue by adaiguoguo** [robGoods/sams#44]
在支付的时候会报这个错

**Comment by iscod** [comment]
> 

更新版本，昨天修复过了

**Comment by maybeqwe** [comment]
> > 
> 
> 更新版本，昨天修复过了

请问更新的hack添加好了优惠券ID，但是下单的时候出现:下单失败：获取履约配送信息异常
这个应该怎么办呢？尝试换StoreDeliveryTemplateId吗？

**Comment by iscod** [comment]
> StoreDeliveryTemplateId

master版本昨天的优惠券有问题，hack上午才更新。你先更新下代码，再尝试换StoreDeliveryTemplateId。hack现在也不太好用了

**Comment by shifanhu** [comment]
> > > 
> > 
> > 
> > 更新版本，昨天修复过了
> 
> 请问更新的hack添加好了优惠券ID，但是下单的时候出现:下单失败：获取履约配送信息异常 这个应该怎么办呢？尝试换StoreDeliveryTemplateId吗？

我试着换了一下 还是不太好用 一会购物异常 一会履约失败的

**Comment by JONREAN2** [comment]
> > StoreDeliveryTemplateId
> 
> master版本昨天的优惠券有问题，hack上午才更新。你先更新下代码，再尝试换StoreDeliveryTemplateId。hack现在也不太好用了

是不是后台做了校验
