### ISSUE TITLE
下单失败：获取履约配送信息异常

### ISSUE THREAD

**Issue by zhengchang907** [robGoods/sams#45]
hack分支

########## 获取当前可用配送时间【03:13:25】 ###########
配送时间： 2022/04/20 周三 09:00 - 18:00, 是否可用：false
发现可用的配送时段::2022/04/20 周三 09:00 - 18:00!
########## 提交订单中【03:13:27】 ###########
下单失败：获取履约配送信息异常

**Comment by zhengchang907** [comment]
duplicated

**Comment by XingyuRenSJTU** [comment]
同样的问题。。还没有抢到。。
