### ISSUE TITLE
下单失败：获取履约配送信息异常

### ISSUE THREAD

**Issue by zhoubo518** [robGoods/sams#46]
更新后提示：
下单失败：获取履约配送信息异常

**Comment by pengliangyou** [comment]
下单失败：获取履约配送信息异常

请问这个是什么错误呢？

**Comment by iscod** [comment]
> 下单失败：获取履约配送信息异常
> 
> 请问这个是什么错误呢？

店铺更新了履约配送信息，造成获取配送信息异常。最新版本已处理该错误类型

**Comment by pengliangyou** [comment]
我更新到最新版本之后还是会报错 😂

########## 获取当前可用配送时间【08:58:52】 ###########
发现可用的配送时段::2022/06/10 周五 09:00 - 18:00!
########## 提交订单中【08:58:53】 ###########
配送时段: 2022/06/10 周五 09:00 - 18:00!
下单失败：获取履约配送信息异常

**Comment by iscod** [comment]
> 

 浦东吗？

**Comment by pengliangyou** [comment]
嗯 是的

**Comment by iscod** [comment]
> 嗯 是的

封闭小区吗？我浦东的正常啊，你运行参数都是什么？

**Comment by pengliangyou** [comment]
已经复工了，参数只用了 token 和 promotionId

**Comment by pengliangyou** [comment]
########## 获取地址附近可用商店 ###########
[0] Id：4807 名称：上海浦东店, 类型 ：2
[1] Id：9996 名称：山姆全球购保税宁波店, 类型 ：8
########## 获取购物车中有效商品【10:14:57】 ###########
[0] 爱他美 进口儿童配方调制乳粉4段  36-72个月  800g*6 数量：1 总价：102300 * 1, 是否勾选： true 
########## 开始校验当前商品【10:14:57】 ###########
运费： 0
########## 获取当前可用配送时间【10:14:58】 ###########
当前无可用配送时间段

########## 获取当前可用配送时间【10:13:15】 ###########
发现可用的配送时段::2022/06/10 周五 09:00 - 18:00!
########## 提交订单中【10:13:15】 ###########
配送时段: 2022/06/10 周五 09:00 - 18:00!
下单失败：获取履约配送信息异常

**Comment by iscod** [comment]
> ########## 获取地址附近可用商店 ########### [0] Id：4807 名称：上海浦东店, 类型 ：2 [1] Id：9996 名称：山姆全球购保税宁波店, 类型 ：8 ########## 获取购物车中有效商品【10:14:57】 ########### [0] 爱他美 进口儿童配方调制乳粉4段 36-72个月 800g*6 数量：1 总价：102300 * 1, 是否勾选： true ########## 开始校验当前商品【10:14:57】 ########### 运费： 0 ########## 获取当前可用配送时间【10:14:58】 ########### 当前无可用配送时间段
> 
> ########## 获取当前可用配送时间【10:13:15】 ########### 发现可用的配送时段::2022/06/10 周五 09:00 - 18:00! ########## 提交订单中【10:13:15】 ########### 配送时段: 2022/06/10 周五 09:00 - 18:00! 下单失败：获取履约配送信息异常

我刚刚还成功一单，可能是你的商品有满减的问题。我试下这个商品

```
########## 获取当前可用配送时间【10:13:08】 ###########
发现可用的配送时段::2022/06/10 周五 09:00 - 18:00!
########## 提交订单中【10:13:09】 ###########
配送时段: 2022/06/10 周五 09:00 - 18:00!
抢购成功，请前往app付款！
```

**Comment by pengliangyou** [comment]
好的 谢谢大佬

**Comment by iscod** [comment]
> ########## 获取地址附近可用商店 ########### [0] Id：4807 名称：上海浦东店, 类型 ：2 [1] Id：9996 名称：山姆全球购保税宁波店, 类型 ：8 ########## 获取购物车中有效商品【10:14:57】 ########### [0] 爱他美 进口儿童配方调制乳粉4段 36-72个月 800g*6 数量：1 总价：102300 * 1, 是否勾选： true ########## 开始校验当前商品【10:14:57】 ########### 运费： 0 ########## 获取当前可用配送时间【10:14:58】 ########### 当前无可用配送时间段
> 
> ########## 获取当前可用配送时间【10:13:15】 ########### 发现可用的配送时段::2022/06/10 周五 09:00 - 18:00! ########## 提交订单中【10:13:15】 ########### 配送时段: 2022/06/10 周五 09:00 - 18:00! 下单失败：获取履约配送信息异常

应该是这个商品问题，我研究下，我购物车加这个商品也是报错

```
########## 获取购物车中有效商品【10:18:14】 ###########
[0] 爱他美 进口儿童配方调制乳粉4段  36-72个月  800g*6 数量：1 总价：102300 * 1, 是否勾选： true 
########## 开始校验当前商品【10:18:15】 ###########
运费： 0
########## 获取当前可用配送时间【10:18:15】 ###########
发现可用的配送时段::2022/06/10 周五 09:00 - 18:00!
########## 提交订单中【10:18:15】 ###########
配送时段: 2022/06/10 周五 09:00 - 18:00!
下单失败：获取履约配送信息异常
```

**Comment by iscod** [comment]
> 好的 谢谢大佬

拉下代码。这个商品的配送信息和其他商品不同，是下周才发货，下单前程序未校验商品和履约信息是否匹配。

这个bug已修复了。

```
########## 获取购物车中有效商品【10:58:22】 ###########
[0] 爱他美 进口儿童配方调制乳粉4段  36-72个月  800g*6 数量：1 总价：102300 * 1, 是否勾选： true 
########## 开始校验当前商品【10:58:22】 ###########
运费： 0
########## 获取当前可用配送时间【10:58:23】 ###########
发现可用的配送时段::2022/06/15 周三 09:00 - 21:00!
发现可用的配送时段::2022/06/16 周四 09:00 - 21:00!
########## 提交订单中【10:58:23】 ###########
配送时段: 2022/06/15 周三 09:00 - 21:00!
下单失败：当前配送时间段已约满，请重新选择配送时段
```

**Comment by iscod** [comment]
> 好的 谢谢大佬

现在可以下单成功，有运力

```
########## 获取购物车中有效商品【16:19:05】 ###########
[0] 爱他美 进口儿童配方调制乳粉4段  36-72个月  800g*6 数量：1 总价：102300 * 1, 是否勾选： true
########## 开始校验当前商品【16:19:06】 ###########
运费： 0
########## 获取当前可用配送时间【16:19:06】 ###########
发现可用的配送时段::2022/06/17 周五 09:00 - 21:00!
########## 提交订单中【16:19:06】 ###########
配送时段: 2022/06/17 周五 09:00 - 21:00!
抢购成功，请前往app付款！
```

**Comment by pengliangyou** [comment]
感谢大佬😄可以给娃抢奶粉了

**Comment by iscod** [comment]
> 感谢大佬😄可以给娃抢奶粉了

感觉sam's的奶粉不便宜啊，没店里的便宜
