### ISSUE TITLE
你好，用的1.2版本cmd无法运行麻烦看下谢谢

### ISSUE THREAD

**Issue by a872238885** [robGoods/sams#48]
显示不是内部命令
Microsoft Windows [版本 10.0.17134.1304]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\steven> cd C:\Users\steven\Desktop\sams-1.2

C:\Users\steven\Desktop\sams-1.2>go run main.go
'go' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\steven\Desktop\sams-1.2>go run main.go --authToken=241c9d961cb6451785b60fce6b38a59e
'go' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\steven\Desktop\sams-1.2>

**Comment by iscod** [comment]
安装go

**Comment by iscod** [comment]
安装go
