### ISSUE TITLE
﻿请问怎么查看authToken,谢谢

### ISSUE THREAD

**Issue by 51033044** [robGoods/sams#49]
﻿请问怎么查看authToken,谢谢

**Comment by jifuwei** [comment]
微信小程序登录山姆，抓取head里面的authtoken,比较方便

**Comment by iscod** [comment]
> 您好，问一下我使用Fiddler，查看微信小程序中的山姆（Result:200）,但是Header中没看到authtoken相关字眼，这个是在（inspectors）中去找吗？期待您的解答

截图发下
