### ISSUE TITLE
请问这个提示是因为被墙的原因么

### ISSUE THREAD

**Issue by peng530** [robGoods/sams#5]
go: github.com/tidwall/gjson@v1.14.0: Get "https://proxy.golang.org/github.com/tidwall/gjson/@v/v1.14.0.mod": dial tcp 142.251.42.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by gyf19** [comment]
设置 goproxy 参数； 参考：https://goproxy.cn/

**Comment by peng530** [comment]
谢谢，解决了
go env -w GOPROXY=https://goproxy.cn,direct
