### ISSUE TITLE
请问是不是20:59:00的时候运力直接从明天变成隔天是不是就是代表没放运力

### ISSUE THREAD

**Issue by CatJuiceQAQ** [robGoods/sams#50]

**Comment by iscod** [comment]
> No description provided.

不清楚，应该是吧，前两天运力都拍到26号了

**Comment by maybeqwe** [comment]
> > No description provided.
> 
> 不清楚，应该是吧，前两天运力都排到26号了

大佬，请问会有新的类似hack版本出来吗？ master版本挂了一晚上都没下单成功0.0

**Comment by iscod** [comment]
> > > No description provided.
> > 
> > 
> > 不清楚，应该是吧，前两天运力都排到26号了
> 
> 大佬，请问会有新的类似hack版本出来吗？ master版本挂了一晚上都没下单成功0.0

没有，有了会更新的

**Comment by maybeqwe** [comment]
> > > > No description provided.
> > > 
> > > 
> > > 不清楚，应该是吧，前两天运力都排到26号了
> > 
> > 
> > 大佬，请问会有新的类似hack版本出来吗？ master版本挂了一晚上都没下单成功0.0
> 
> 没有，有了会更新的

好的，拜谢大佬
