### ISSUE TITLE
刚刚释放运力了还是显示履约时间问题

### ISSUE THREAD

**Issue by JONREAN2** [robGoods/sams#51]
master 也不能用了吗

**Comment by iscod** [comment]
> master 也不能用了吗

可以下单啊，测试其它城市没问题

**Comment by bwlx** [comment]
9:30 抢到了，那时候刚好重启了一下程序

**Comment by NeverArgueWithGF** [comment]
> 9:30 抢到了，那时候刚好重启了一下程序

极速达还是全城配呀？

**Comment by bwlx** [comment]
> > 9:30 抢到了，那时候刚好重启了一下程序
> 
> 极速达还是全城配呀？

全城配

**Comment by iscod** [comment]
> > 9:30 抢到了，那时候刚好重启了一下程序
> 
> 极速达还是全城配呀？

极速达开了？

**Comment by NeverArgueWithGF** [comment]
> > > 9:30 抢到了，那时候刚好重启了一下程序
> > 
> > 
> > 极速达还是全城配呀？
> 
> 极速达开了？



> > > 9:30 抢到了，那时候刚好重启了一下程序
> > 
> > 
> > 极速达还是全城配呀？
> 
> 极速达开了？

有的地区有极速达 今天有人抢到
