### ISSUE TITLE
[Enhancement] 能否做个哨兵版本监控保供套餐的出现

### ISSUE THREAD

**Issue by hugulas** [robGoods/sams#52]
我不会go，只会java和python，只能为作者尽可能把effort减小，希望考虑这个增强。

功能描述
1. 通过搜索保供套餐，关键字“保供”
2. 取得应答
3. 如果搜索结果有效，bark提醒，打印出保供套餐内容

**请求：**

```
 |POST /api/v1/sams/goods-portal/spu/search HTTP/1.1

Host | api-sams.walmartmobile.cn
Accept | */*
auth-token | xxx
device-type | mini_program
Accept-Encoding | gzip, deflate, br
Accept-Language | en-us
Content-Type | application/json;charset=utf-8
Content-Length | 483
User-Agent | Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E217 MicroMessenger/6.8.0(0x16080000) NetType/WIFI Language/en Branch/Br_trunk MiniProgramEnv/Mac
Connection | keep-alive
system-language | CN
Referer | https://servicewechat.com/wxb344a8513eaaf849/229/page-frame.html
```
**请求JSON：**
{"channelType":2,"addressVO":{},"filter":[],"keyword":"保供","excludeSpuIds":[],"pageNum":1,"pageSize":20,"sort":"0","sortType":"","storeInfoVOList":[{"storeDeliveryAttr":[10],"storeId":"9991","storeType":32},{"storeDeliveryAttr":[2,3,4,5,6,7,12],"storeId":"4807","storeType":2},{"storeDeliveryAttr":[3,4],"storeId":"6683","storeType":4},{"storeDeliveryAttr":[1],"storeId":"9996","storeType":8}],"userUid":"需要替换","uid":"268577174","appId":"需要替换","saasId":"1818"}

**应答：**
{"data":{"pageNum":1,"pageSize":20,"totalCount":1,"dataList":[{"spuId":"替换","storeId":"4807","seriesId":"39500140","title":"保供套餐A","subTitle":"套餐内容:MM芝士华夫饼1.08kg+荷美尔牛肉干 350g+MM夏威夷果仁 500g+口福莱榛子仁牛奶巧克力500g+MM椰子水 200ml*24","brandId":"10196732","categoryIdList":["10012335","10012336"],"masterBizType":1,"viceBizType":1,"image":"https://sam-material-online-1302115363.file.myqcloud.com//sams-static/goods/4473518/12d50a95-e35e-4d2d-9876-0a6c93fe75b1.jpg","giveaway":false,"isAvailable":true,"isPutOnSale":true,"priceInfo":[{"priceType":4,"price":"51460","priceTypeName":"锁价"},{"priceType":1,"price":"51460","priceTypeName":"销售价"}],"limitInfo":[{"limitType":4,"limitNum":1,"text":"1件/人/天","storeId":"4807"}],"tagInfo":[{"title":"限购1件","tagPlace":0,"tagMark":"PURCHASE_LIMIT"},{"title":"新品","tagPlace":1,"tagMark":"upperLeft"}],"deliveryAttr":3,"isPresell":false,"algId":"sr-search-layer-sam@82,sr-search-layer-sam@82","searchId":"替换","requestId":"替换","positionId":1,"page":1,"beltInfo":[],"hasVideo":false}],"hasNextPage":false,"onlyShowSimilarButton":false,"SearchService":{"bid":"替换","query":"保供","sceneId":"替换","requestId":"替换","sequenceId":"替换","algId":"sr-search-layer-sam@82,sr-search-layer-sam@82"}},"code":"Success","msg":"","errorMsg":"","traceId":"替换","requestId":"替换","rt":0,"success":true}

**Comment by 2dot4** [comment]
今天保供套餐都是零食，挺坑的

**Comment by iscod** [comment]
没运力，只有商品还是下不了单啊。。。

**Comment by hugulas** [comment]
我都下单成功了

**Comment by hugulas** [comment]
https://github.com/azhan1998/sam_buy/pull/37

@iscod 不做也罢，我写了个python的

**Comment by iscod** [comment]
> [azhan1998/sam_buy#37](https://github.com/azhan1998/sam_buy/pull/37)
> 
> @iscod 不做也罢，我写了个python的

这个项目我看过，原理都差不多。能抢到菜，实现需求就是好项目
