### ISSUE TITLE
能不能建议加一个更新购物车 更新配送时间的功能 

### ISSUE THREAD

**Issue by JONREAN2** [robGoods/sams#54]
非常感谢 

一直没抢到

**Comment by iscod** [comment]
> 非常感谢
> 
> 一直没抢到

购物车更新不频繁，没必要自动更新吧？

**Comment by JONREAN2** [comment]
> > 非常感谢
> > 一直没抢到
> 
> 购物车更新不频繁，没必要自动更新吧？

这几天有时候上架 有时间下架的，还有提交的时候，某个物品缺货 也能拍吗?

**Comment by iscod** [comment]
> 

提示缺货会去刷购物车，再重新提交

**Comment by hugulas** [comment]
可以写个crontab自动杀死老进程，然后重启新进程，不需要实现。

**Comment by iscod** [comment]
> 可以写个crontab自动杀死老进程，然后重启新进程，不需要实现。

里面有个sh，可以改下
