### ISSUE TITLE
想问下没有GO环境在release里面下载exe程序直接运行就可以吗？

### ISSUE THREAD

**Issue by haifengdeweidao** [robGoods/sams#56]
我下载到自己的windows下面双击exe程序没有反应，不知道是不是需要什么前置操作。。

**Comment by iscod** [comment]
> 我下载到自己的windows下面双击exe程序没有反应，不知道是不是需要什么前置操作。。

双击应该是不行，应该是在cmd模式下，运行。类似与linux下运行
