### ISSUE TITLE
请问我的购物车中有商品为什么一直提示无有效商品

### ISSUE THREAD

**Issue by haifengdeweidao** [robGoods/sams#57]
刚自己摸索了下安装了GO环境，按照大佬的提示运行了GO程序，我只选择了自己的收货地址，程序就开始自动运行，但一直提示没有有效商品，请问是不是还需要选择对应的是哪个仓库才行？但我选择收货地址后就自动运行没法再选对应仓库

**Comment by iscod** [comment]
> 刚自己摸索了下安装了GO环境，按照大佬的提示运行了GO程序，我只选择了自己的收货地址，程序就开始自动运行，但一直提示没有有效商品，请问是不是还需要选择对应的是哪个仓库才行？但我选择收货地址后就自动运行没法再选对应仓库

不需要，选对地址即可，你登陆app看下购物车，应该是购物车里的商品都下架了

**Comment by haifengdeweidao** [comment]
> > 刚自己摸索了下安装了GO环境，按照大佬的提示运行了GO程序，我只选择了自己的收货地址，程序就开始自动运行，但一直提示没有有效商品，请问是不是还需要选择对应的是哪个仓库才行？但我选择收货地址后就自动运行没法再选对应仓库
> 
> 不需要，选对地址即可，你登陆app看下购物车，应该是购物车里的商品都下架了

我在app里添加了一个可以极速达的纸尿裤，手动结账可以进入结算页面，不过代码这边确实提示的是没有有效商品 ：捂脸

**Comment by iscod** [comment]
> 

你运行时的  -deliveryType的参数是什么？默认是2，全城配送不是极速达。两个方式的购物车物品不同

**Comment by haifengdeweidao** [comment]
> 

我在main.go的代码里直接把deliveryType的数值改成1可以吗？

**Comment by haifengdeweidao** [comment]
> > 
> 
> 你运行时的 -deliveryType的参数是什么？默认是2，全城配送不是极速达。两个方式的购物车物品不同

我刚才直接改了main.go的参数可以了，有个下单失败的403报错说“很抱歉，您提交的请求可能对网站造成威胁，请求已被管理员设置的策略阻断”，这是被屏蔽了的意思吗。。

**Comment by iscod** [comment]
> > 
> 
> 我在main.go的代码里直接把deliveryType的数值改成1可以吗？

可以

**Comment by iscod** [comment]
> > > 
> > 
> > 
> > 你运行时的 -deliveryType的参数是什么？默认是2，全城配送不是极速达。两个方式的购物车物品不同
> 
> 我刚才直接改了main.go的参数可以了，有个下单失败的403报错说“很抱歉，您提交的请求可能对网站造成威胁，请求已被管理员设置的策略阻断”，这是被屏蔽了的意思吗。。

参考 #15 跟你的情况一样，好像是有个参数设置为空字符串就可以了

**Comment by haifengdeweidao** [comment]
> 

看到了大佬，那位同学是说trackinfo设置成空字段，我去代码里看了下目前就是空字段，可能腾讯的阻断策略又升级了。
不过目前乐观的是虽然有报错，但还是有些成功下单的情况，目前看并不是全部都会拦截。

**Comment by iscod** [comment]
> 些成功下单的情况，目前看并

所以这个策略到底是个啥，为啥我一次都没遇到过。。。。

**Comment by haifengdeweidao** [comment]
> > 些成功下单的情况，目前看并
> 
> 所以这个策略到底是个啥，为啥我一次都没遇到过。。。。

所以是我们几个老哥中头彩了么哈哈哈 捂脸
