### ISSUE TITLE
请问如何填入barkId，是填在main.go以记事本打开吗？但是填在哪里呢？

### ISSUE THREAD

**Issue by standynamite** [robGoods/sams#60]
go已装，包已抓，authtoken已经获得了，但是有个barkid问题不明白怎么去修改参数
是直接=后面删除了 填入barkid吗？
main.go记事本打开了
barkId       = flag.String("barkId", "", "可选，通知用的`bark` id, 可选参数")

我没有编程基础，但是抢购不到东西要想办法活下去

**Comment by iscod** [comment]
> authtoken

在运行命令后面加参数就行了

```sh
go run main.go --authToken=xxxxx --barkId=xxxx
```

**Comment by standynamite** [comment]
好的 明白了。谢谢大佬
