### ISSUE TITLE
sams-v1.3-amd64（.exe）无法在win7系统中运行

### ISSUE THREAD

**Issue by Young-Coder** [robGoods/sams#63]
release中的.exe无法打开，v1.1，v1.2都不行。请问，这个问题如何解决？非常感谢~

**Comment by iscod** [comment]
> release中的.exe无法打开，v1.1，v1.2都不行。请问，这个问题如何解决？非常感谢~

报错信息发下？是64位系统吧？实在不行源码下载运行
