### ISSUE TITLE
早上8点运行一直购物车无有效商品

### ISSUE THREAD

**Issue by j5land** [robGoods/sams#64]
如题。
等到8点半，重新运行程序，就能查询到商品了。
但这样错过了抢购最佳时间。
请问大家有没有出现这种类似情况？
程序自动运行一直查询购物车无有效商品，程序重新运行是能查询到的。

下图是第二次运行能查询到商品，但是错过了配送被抢完了。
![20220501083151](https://user-images.githubusercontent.com/1421509/166127210-034a7541-2dec-4274-8b40-a1e1bace0519.jpg)

**Comment by j5land** [comment]
自己代码修改好了

**Comment by iscod** [comment]
> 自己代码修改好了

？？？？pull 上看看

**Comment by j5land** [comment]
> > 自己代码修改好了
> 
> ？？？？pull 上看看

比较简单的，这个是一个特殊场景：
门店没开放，比如：上海普陀DC店，并不是一直开着的。
所以第一次运行无法查询到门店信息；
CheckCart 的时候没有这家门店信息，没有这家门店信息；
再次运行，门店已上线，就能查询到对应购物车商品信息了；
所以，我认为CheckCart 要与 GetStoreList（要刷新） 联动。

**Comment by iscod** [comment]
> > > 自己代码修改好了
> > 
> > 
> > ？？？？pull 上看看
> 
> 比较简单的，这个是一个特殊场景： 门店没开放，比如：上海普陀DC店，并不是一直开着的。 所以第一次运行无法查询到门店信息； CheckCart 的时候没有这家门店信息，没有这家门店信息； 再次运行，门店已上线，就能查询到对应购物车商品信息了； 所以，我认为CheckCart 要与 GetStoreList（要刷新） 联动。

ok，我明天测试下

**Comment by iscod** [comment]
> 

尝试用下最新版本的商店预加载，在店铺未上线之前，其实就有库存了，可以用预加载的方式而非接口请求获取到有库存的商品和运力
