### ISSUE TITLE
Release版本问题

### ISSUE THREAD

**Issue by dannycxh** [robGoods/sams#65]
release 版本里 
  -barkId bark
    	可选，通知用的bark id, 可选参数
  -deliveryType int
    	可选，1 急速达，2， 全程配送 (default 2)
  -floorId int
    	可选，1,普通商品 2,全球购保税 3,特殊订购自提 4,大件商品 5,厂家直供商品 6,特殊订购商品 7,失效商品 (default 1)

这几个参数如何获取？

**Comment by iscod** [comment]
如何获取什么意思？你下单选择什么就用对应选项，不知道就先默认
