### ISSUE TITLE
缺货商品强制添加购物车

### ISSUE THREAD

**Issue by ThrowDice** [robGoods/sams#67]
有些商品没货就加不了购物车，得一直check是不是有货，添加了之后再抢。能不能有办法强制加到购物车（在购物车里显示为以下商品无货，暂不支持购买），这样就能一直跑，什么时候出现库存了就可以抢。

**Comment by iscod** [comment]
> 有些商品没货就加不了购物车，得一直check是不是有货，添加了之后再抢。能不能有办法强制加到购物车（在购物车里显示为以下商品无货，暂不支持购买），这样就能一直跑，什么时候出现库存了就可以抢。

两种方案：
1. 手机app里面切换到其它城市的地址，把商品加到购物就可以，商品的spuId是公用的，只是门店信息不同。这样就加到购物车了。
1. 手机app里面无货商品也是可以操作加入购物车的

**Comment by gyf19** [comment]
@iscod  可以增加一个最低订单价格设置。  场景是： 购物车里无货商品 ， 突然上架某件商品就下单成功。

**Comment by iscod** [comment]
> @iscod 可以增加一个最低订单价格设置。 场景是： 购物车里无货商品 ， 突然上架某件商品就下单成功。

最新版本有一个-deliveryFee参数，校验达到订单免运费时才下单

**Comment by iscod** [comment]
> 有些商品没货就加不了购物车，得一直check是不是有货，添加了之后再抢。能不能有办法强制加到购物车（在购物车里显示为以下商品无货，暂不支持购买），这样就能一直跑，什么时候出现库存了就可以抢。

山姆，微信小程序，搜索想要的东西，缺货也可以加到购物车
