### ISSUE TITLE
客户端更新商品库存 插件不更新

### ISSUE THREAD

**Issue by riskgod** [robGoods/sams#69]
如题，是否是因为先检测配送时间 后检测可下单产品的？ 已经拉了最新代码 go run main.go 跑的

**Comment by iscod** [comment]
> 如题，是否是因为先检测配送时间 后检测可下单产品的？ 已经拉了最新代码 go run main.go 跑的

程序需要确认有运力和库存两个条件时，才会下单，所有并不是实时更新购物车中商品的库存。这是流程式无法避免的问题。
v2版本我准备做成并发式，实时去监测库存和运力。

**Comment by zangzimi** [comment]
是不是不需要并发式这么复杂，比如在检查运力流程，判断和上次刷新购物车时间超过一定时间（比如一分钟）就进入刷新购物车环节？顺便说一句，感谢 @iscod ，实在太厉害了！
