### ISSUE TITLE
请教使用中问题

### ISSUE THREAD

**Issue by devil-red123456** [robGoods/sams#7]
请教：
我20：57分开始运行程序，但是
一开始报如下错误：
<img width="878" alt="image" src="https://user-images.githubusercontent.com/103564524/163399784-80b048f2-fe94-4ecf-88f0-aeaf80efe76c.png">
后面能进去选择了地址和付款方式，又出现一下错误
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/103564524/163400045-8758d2b9-ed8f-4d5a-b730-5b6f634a94e6.png">
请问出现上述错误是正常的吗？
谢谢！
另外再请教一下：
main.go文件中：
		Longitude:    "xxxxx", //HTTP头部longitude
		Latitude:     "xxxxx", //HTTP头部latitude
		Deviceid:     "xxxxx", //HTTP头部device-id
		Trackinfo:    `xxxxx`, // HTTP头部track-info
这几项需要填吗？谢谢！！

**Comment by KirbyInGitHub** [comment]
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/11568406/163407064-7022f20b-47db-42dc-b260-a7f70080c4f8.png">
在轮询可用地址的时候，服务器超时就会重新校验商品，这时候就会一直报错，必须手动结束掉重新开始才能正常，试了好几次都是这样的。

**Comment by devil-red123456** [comment]
> > 请教： 我20：57分开始运行程序，但是 一开始报如下错误： <img alt="image" width="878" src="https://user-images.githubusercontent.com/103564524/163399784-80b048f2-fe94-4ecf-88f0-aeaf80efe76c.png"> 后面能进去选择了地址和付款方式，又出现一下错误 <img alt="image" width="1080" src="https://user-images.githubusercontent.com/103564524/163400045-8758d2b9-ed8f-4d5a-b730-5b6f634a94e6.png"> 请问出现上述错误是正常的吗？ 谢谢！ 另外再请教一下： main.go文件中： Longitude: "xxxxx", //HTTP头部longitude Latitude: "xxxxx", //HTTP头部latitude Deviceid: "xxxxx", //HTTP头部device-id Trackinfo: `xxxxx`, // HTTP头部track-info 这几项需要填吗？谢谢！！
> 
> 1. HTTP头部经过测试，只有auth-token必须，其它几个暂时为发现是必须的。
> 2. http超时的问题正常，山姆在21点会经常超时，让程序继续重试即可
> 3. 校验商品的报错也是山姆返回的，让程序自动重试就行，建议在早点时间运行，获取地址，校验商品理论只需要运行成功一次就可以

谢谢！！

**Comment by iscod** [comment]
> <img alt="image" width="1073" src="https://user-images.githubusercontent.com/11568406/163407064-7022f20b-47db-42dc-b260-a7f70080c4f8.png">
> 
> 在轮询可用派送时间段的时候，服务器超时就会重新校验商品，这时候就会一直报错，必须手动结束掉重新开始才能正常，试了好几次都是这样的，没有办法自动重试到校验成功。 这里派送获取超时了，是不是可以重新获取而不必重新校验。

超时的错误处理应该是设置成了从第一步开始，等我坐下超时的错误处理吧

**Comment by peng530** [comment]
有成功的么？获得时间后一直在校验商品。

**Comment by iscod** [comment]
> 有成功的么？获得时间后一直在校验商品。

截图发一下

**Comment by peng530** [comment]
> 

仔细看了下log，不是获取时间后再校验商品，应该跟问题描述的一样是超时了重新校验。然后一直报错。

**Comment by iscod** [comment]
> 间后再校验商品，应该跟问题描述的一样是超

当前校验商品有一个bug，就是app中的购物车地址和程序选择地址不同时，会校验失败，这是因为程序没调用保存地址到sam‘s。

这个bug已经修复，你可以更新最新代码试下

另外超时后的错误处理确实有问题，目前还没更新

**Comment by peng530** [comment]
> > 间后再校验商品，应该跟问题描述的一样是超
> 
> 当前校验商品有一个bug，就是app中的购物车地址和程序选择地址不同时，会校验失败，这是因为程序没调用保存地址到sam‘s。
> 
> 这个bug已经修复，你可以更新最新代码试下
> 
> 另外超时后的错误处理确实有问题，目前还没更新

好的，谢谢，那超时后就先手动重启吧

**Comment by iscod** [comment]
> > > 间后再校验商品，应该跟问题描述的一样是超
> > 
> > 
> > 当前校验商品有一个bug，就是app中的购物车地址和程序选择地址不同时，会校验失败，这是因为程序没调用保存地址到sam‘s。
> > 这个bug已经修复，你可以更新最新代码试下
> > 另外超时后的错误处理确实有问题，目前还没更新
> 
> 好的，谢谢，那超时后就先手动重启吧

轮询可用派送时间段超时，会重新校验商品这个问题已经修了

**Comment by peng530** [comment]
> > > > 间后再校验商品，应该跟问题描述的一样是超
> > > 
> > > 
> > > 当前校验商品有一个bug，就是app中的购物车地址和程序选择地址不同时，会校验失败，这是因为程序没调用保存地址到sam‘s。
> > > 这个bug已经修复，你可以更新最新代码试下
> > > 另外超时后的错误处理确实有问题，目前还没更新
> > 
> > 
> > 好的，谢谢，那超时后就先手动重启吧
> 
> 轮询可用派送时间段超时，会重新校验商品这个问题已经修了

晚上成功了，👍

**Comment by iscod** [comment]
> > > > > 间后再校验商品，应该跟问题描述的一样是超
> > > > 
> > > > 
> > > > 当前校验商品有一个bug，就是app中的购物车地址和程序选择地址不同时，会校验失败，这是因为程序没调用保存地址到sam‘s。
> > > > 这个bug已经修复，你可以更新最新代码试下
> > > > 另外超时后的错误处理确实有问题，目前还没更新
> > > 
> > > 
> > > 好的，谢谢，那超时后就先手动重启吧
> > 
> > 
> > 轮询可用派送时间段超时，会重新校验商品这个问题已经修了
> 
> 晚上成功了，👍

今天也能成功？今天下午山姆所有都下架了。。。

**Comment by peng530** [comment]
> > > > > > 间后再校验商品，应该跟问题描述的一样是超
> > > > > 
> > > > > 
> > > > > 当前校验商品有一个bug，就是app中的购物车地址和程序选择地址不同时，会校验失败，这是因为程序没调用保存地址到sam‘s。
> > > > > 这个bug已经修复，你可以更新最新代码试下
> > > > > 另外超时后的错误处理确实有问题，目前还没更新
> > > > 
> > > > 
> > > > 好的，谢谢，那超时后就先手动重启吧
> > > 
> > > 
> > > 轮询可用派送时间段超时，会重新校验商品这个问题已经修了
> > 
> > 
> > 晚上成功了，👍
> 
> 今天也能成功？今天下午山姆所有都下架了。。。

下单的是青浦的山姆，不知道能不能送。
