### ISSUE TITLE
"下单失败：楼层ID不合法"

### ISSUE THREAD

**Issue by alucard-ltd** [robGoods/sams#70]
脚本自动下单时，一直报这个错。

**Comment by iscod** [comment]
> 脚本自动下单时，一直报这个错。

运行参数是什么？

**Comment by alucard-ltd** [comment]
> > 脚本自动下单时，一直报这个错。
> 
> 运行参数是什么？

加了token和 barkid

**Comment by iscod** [comment]
> > 自动下单时，一直报这个错。
> 
> 运行参数

最新版本吗？
