### ISSUE TITLE
-addressId无效，每次进去还是需要选择一下。。。

### ISSUE THREAD

**Issue by fengwuxiaozi** [robGoods/sams#73]
-addressId无效，每次进去还是需要选择一下。。。

**Comment by iscod** [comment]
> -addressId无效，每次进去还是需要选择一下。。。

大概率是你的id不对，id对应的是山姆的id，不是每次选择的序号

**Comment by fengwuxiaozi** [comment]
好吧，进去代码看了下。。。是山姆给编的那个地址id。。。不是0123这种。。。

**Comment by iscod** [comment]
> 好吧，进去代码看了下。。。是山姆给编的那个地址id。。。不是0123这种。。。

对
