### ISSUE TITLE
不好意思小白一个，请教一下releases版本下载运行了，怎么输入所需要的参数呀。谢谢！！

### ISSUE THREAD

**Issue by crashXG** [robGoods/sams#74]

**Comment by iscod** [comment]
> _No description provided._

--help 看下提示

**Comment by crashXG** [comment]
不好意思，在哪里输入--help呀？在mac 终端运行了之后就是显示进程已完成，似乎无法输入

**Comment by iscod** [comment]
> 不好意思，在哪里输入--help呀？在mac 终端运行了之后就是显示进程已完成，似乎无法输入

你下载下来的那个版本？文件名叫什么？终端运行截图发下

**Comment by crashXG** [comment]
<img width="815" alt="截屏2022-05-12 15 47 37" src="https://user-images.githubusercontent.com/105404759/168019521-b6374977-b79c-4ccd-9bce-a78aa5dbdddf.png">
下载的是sams-v1.5-amd64.darwin版本，mac

**Comment by iscod** [comment]
> <img alt="截屏2022-05-12 15 47 37" width="815" src="https://user-images.githubusercontent.com/105404759/168019521-b6374977-b79c-4ccd-9bce-a78aa5dbdddf.png">
> 
> 下载的是sams-v1.5-amd64.darwin版本，mac

你是直接鼠标点击的文件吧？

**Comment by crashXG** [comment]
对的

**Comment by iscod** [comment]
> 对的

你再Mac的APP里面，先打开终端。

然后把文件拖到终端里面，再按回车

**Comment by iscod** [comment]
你的文件下载到那个目录了？

**Comment by crashXG** [comment]
我只下载了一个released文件，在download下的一个subfolder

**Comment by iscod** [comment]
> 我只下载了一个released文件，在download下的一个subfolder

打开终端直接输入下面的命令，回车看下结果

```sh
 ~/Downloads/subfolder/sams-v1.5-amd64.darwin --authToken=xxxx
```

**Comment by crashXG** [comment]
显示no such file or director
<img width="638" alt="截屏2022-05-12 16 11 23" src="https://user-images.githubusercontent.com/105404759/168023696-e7eb076b-0a32-4a89-80a1-890e1b2629a7.png">
y

**Comment by iscod** [comment]
你文件是下载到 Downloads目录下subfolder下了吧？大小写对吗？

**Comment by crashXG** [comment]
对的，第一张图是我把文件直接拖进终端显示的路径。
<img width="638" alt="截屏2022-05-12 16 18 43" src="https://user-images.githubusercontent.com/105404759/168025352-076d5a03-61a8-41ec-8a4d-d35318f873aa.png">
<img width="638" alt="截屏2022-05-12 16 19 46" src="https://user-images.githubusercontent.com/105404759/168025434-80a17d55-4860-4a66-979e-7f238abf309b.png">

，我又试了一下，出来的是这个。

**Comment by iscod** [comment]
你别麻烦了，直接鼠标拖拽目录到终端里面，回车

然后输入下面的命令，看下结果
```
./sams-v1.5-amd64.darwin --authToken=xxxx
```

**Comment by crashXG** [comment]
要哭了。
<img width="682" alt="截屏2022-05-12 16 23 37" src="https://user-images.githubusercontent.com/105404759/168026015-7adbaf8a-42a8-474b-a0ba-8659ff63f8ec.png">
。

**Comment by iscod** [comment]
> 对的，第一张图是我把文件直接拖进终端显示的路径。 <img alt="截屏2022-05-12 16 18 43" width="638" src="https://user-images.githubusercontent.com/105404759/168025352-076d5a03-61a8-41ec-8a4d-d35318f873aa.png"> <img alt="截屏2022-05-12 16 19 46" width="638" src="https://user-images.githubusercontent.com/105404759/168025434-80a17d55-4860-4a66-979e-7f238abf309b.png">
> 
> ，我又试了一下，出来的是这个。


第二张图就是对的，就用这个
```
 ~/Downloads/subfolder/sams-v1.5-amd64.darwin --authToken=xxxx
```

**Comment by iscod** [comment]
> > 对的，第一张图是我把文件直接拖进终端显示的路径。 <img alt="截屏2022-05-12 16 18 43" width="638" src="https://user-images.githubusercontent.com/105404759/168025352-076d5a03-61a8-41ec-8a4d-d35318f873aa.png"> <img alt="截屏2022-05-12 16 19 46" width="638" src="https://user-images.githubusercontent.com/105404759/168025434-80a17d55-4860-4a66-979e-7f238abf309b.png">
> > ，我又试了一下，出来的是这个。
> 
> 第二张图就是对的，就用这个命令，看下结果
> 
> ```
>  ~/Downloads/subfolder/sams-v1.5-amd64.darwin --authToken=xxxx
> ```

**Comment by crashXG** [comment]
> > > 对的，第一张图是我把文件直接拖进终端显示的路径。 <img alt="截屏2022-05-12 16 18 43" width="638" src="https://user-images.githubusercontent.com/105404759/168025352-076d5a03-61a8-41ec-8a4d-d35318f873aa.png"> <img alt="截屏2022-05-12 16 19 46" width="638" src="https://user-images.githubusercontent.com/105404759/168025434-80a17d55-4860-4a66-979e-7f238abf309b.png">
> > > ，我又试了一下，出来的是这个。
> > 
> > 
> > 第二张图就是对的，就用这个命令，看下结果
> > ```
> >  ~/Downloads/subfolder/sams-v1.5-amd64.darwin --authToken=xxxx
> > ```

那我就用这个命令进去，但接着咋输入token和其他的参数呀

**Comment by iscod** [comment]
获取token，可以看这个帖子：https://github.com/robGoods/sams/issues/55

**Comment by iscod** [comment]
> 

对，xxx换成你的token就可以了，默认抢购的14点的全城配订单，你可以13：55的时候就运行起来，一直到到成功，如果到14:30还没成功，基本就没运力了。就可以关了

**Comment by crashXG** [comment]
> > 
> 
> 对，xxx换成你的token就可以了，默认抢购的14点的全城配订单，你可以13：55的时候就运行起来，一直到到成功，如果到14:30还没成功，基本就没运力了。就可以关了
> 
> 不过这几天全城配，脚本基本都能抢到

好的！！谢谢！那保供的话就得需要通过app先加到购物车嘛？

**Comment by iscod** [comment]
> > > 
> > 
> > 
> > 对，xxx换成你的token就可以了，默认抢购的14点的全城配订单，你可以13：55的时候就运行起来，一直到到成功，如果到14:30还没成功，基本就没运力了。就可以关了
> > 不过这几天全城配，脚本基本都能抢到
> 
> 好的！！谢谢！那保供的话就得需要通过app先加到购物车嘛？

对，缺货商品可以在微信小程序里面加到购物车
