### ISSUE TITLE
能否加一个option，开关检查isSelected

### ISSUE THREAD

**Issue by futuration** [robGoods/sams#77]
emmm有时候不想全选购物车，谢谢！
另外最近极速达dc的地理围墙变动较频繁。大佬有木有那个，就是那个那个，，，，hack之类的能通过比如areablockid突破限制。。？？嘿嘿

**Comment by iscod** [comment]
> 

抢购还搞isSelected? 极速达dc地理围墙是什么？极速达dc的areablockid基本是固定的。没见过会变动areablockid的。

你可以尝试下商店预加载，具体看在这里： https://github.com/robGoods/sams/issues/76

**Comment by futuration** [comment]
> > 
> 
> 抢购还搞isSelected? 极速达dc地理围墙是什么？极速达dc的areablockid基本是固定的。
> 
> 你可以尝试下商店预加载，具体看在这里： #76

上海各个dc的storetemplateid和areablockid已经变动了好几次了。我甚至已经抓包看到“xx静默（临时区块别占用）“的字样了。我甚至今天通过下单——地址写dc仓地址、详细地址写我自家地址强行下单。这样强行让人工发现并与我联系，最后小哥打电话和我说dc配送范围居然已经缩到1公里内了。

isSelected是因为有些东西并不想删出购物车，但本次姑且还不想买。亦或者有时帮亲戚买，也不想删除购物车。谢谢

**Comment by iscod** [comment]
> > 抢购还搞isSelected? 极速达dc地理围墙是什么？极速达dc的areablockid基本是固定的。
> > 你可以尝试下商店预加载，具体看在这里： #76
> 
> 上海各个dc的storetemplateid和areablockid已经变动了好几次了。我甚至已经抓包看到“xx静默（临时区块别占用）“的字样了。我甚至今天通过下单——地址写dc仓地址、详细地址写我自家地址强行下单。这样强行让人工发现并与我联系，最后小哥打电话和我说dc配送范围居然已经缩到1公里内了。
> 
> 我一直关注着大佬的项目，预加载其实我已经成功配置了。我直接抓包后save response做成文件，比大佬前几个commit里的sh/curl指令来的方便点。 另外，商店一旦变动templateid（就他们系统内等于完全重建了个临时dc配置），预加载也会失效。
> 
> 极速达的地理围墙我自己也不确定，只是瞎猜areablockid。地理围墙是我自己测出来的。我和朋友固定同一个dc覆盖，我离得远他离得近。封城后，我地址（5.4公里行程，非直线距离）在4月中旬还能配送，但5月前后，dc变动配置无法配送了；然后上海静默后，同一个dc第二次变更配置，他的地址（3.4公里行程，非直线距离）也无法配送了。
> 
> isSelected是因为有些东西并不想删出购物车，但本次姑且还不想买。亦或者有时帮亲戚买，也不想删除购物车。谢谢

有一种模式或许可以，在山姆微信小程序中，极速达和全城配的商品是可以一起下单的，我之前分析是两种商品虽然对应的店铺不同，但是可以使用全城配商店的templeid 和areablockid下单。
也就是说可以用全城配商店配置去创建极速达商品的订单。不过我没深入去研究，只是发现了商店预加载可以在未开店铺之前下单

**Comment by iscod** [comment]
-isSelected 参数加上了，可以更新下代码。默认是不做筛选 -isSelected=true是做筛选

**Comment by futuration** [comment]
> > > 抢购还搞isSelected? 极速达dc地理围墙是什么？极速达dc的areablockid基本是固定的。
> > > 你可以尝试下商店预加载，具体看在这里： #76
> > 
> > 
> > 上海各个dc的storetemplateid和areablockid已经变动了好几次了。我甚至已经抓包看到“xx静默（临时区块别占用）“的字样了。我甚至今天通过下单——地址写dc仓地址、详细地址写我自家地址强行下单。这样强行让人工发现并与我联系，最后小哥打电话和我说dc配送范围居然已经缩到1公里内了。
> > 我一直关注着大佬的项目，预加载其实我已经成功配置了。我直接抓包后save response做成文件，比大佬前几个commit里的sh/curl指令来的方便点。 另外，商店一旦变动templateid（就他们系统内等于完全重建了个临时dc配置），预加载也会失效。
> > 极速达的地理围墙我自己也不确定，只是瞎猜areablockid。地理围墙是我自己测出来的。我和朋友固定同一个dc覆盖，我离得远他离得近。封城后，我地址（5.4公里行程，非直线距离）在4月中旬还能配送，但5月前后，dc变动配置无法配送了；然后上海静默后，同一个dc第二次变更配置，他的地址（3.4公里行程，非直线距离）也无法配送了。
> > isSelected是因为有些东西并不想删出购物车，但本次姑且还不想买。亦或者有时帮亲戚买，也不想删除购物车。谢谢
> 
> 有一种模式或许可以，在山姆微信小程序中，极速达和全城配的商品是可以一起下单的，我之前分析是两种商品虽然对应的店铺不同，但是可以使用全城配商店的templeid 和areablockid下单。 也就是说可以用全城配商店配置去创建极速达商品的订单。不过我没深入去研究，只是发现了商店预加载可以在未开店铺之前下单，就没把经历放到这个模式上了

感谢，这个我也去看看

**Comment by iscod** [comment]
> 最后的话，还有一个小细节，大佬可以考虑用math/rand把sleep搞点随机数，不过山姆的腾讯waf风控确实不严格，好像也无所谓。
> 
> 另：附上上海一些dc的地址，不过大佬应该有了？毕竟抓出来就有，大佬需要的话可以把收货地址直接填这些地方，以便测试。 青浦 DC：上海市青浦区盈港路84号一层 松江南DC：人民北路1511号 上大DC：上海宝山区南大路201号3号楼 普陀 DC：上海市普陀区交暨路207弄5号 齐成创业园A座3层302房间 杨浦DC：黄兴路1737号九隆坊B1层 北蔡DC：上海市浦东新区严丰路216号(自由步行街底商） 金桥DC：上海市浦东新区金藏路258号3栋4层 唐镇DC：孙桥镇川北公路 3556号三号楼一层

👌，我有时间研究研究

**Comment by iscod** [comment]
> > > 
> > 
> > 
> > 抢购还搞isSelected? 极速达dc地理围墙是什么？极速达dc的areablockid基本是固定的。
> > 你可以尝试下商店预加载，具体看在这里： #76
> 
> 上海各个dc的storetemplateid和areablockid已经变动了好几次了。我甚至已经抓包看到“xx静默（临时区块别占用）“的字样了。我甚至今天通过下单——地址写dc仓地址、详细地址写我自家地址强行下单。这样强行让人工发现并与我联系，最后小哥打电话和我说dc配送范围居然已经缩到1公里内了。
> 
> 我一直关注着大佬的项目，预加载其实我已经成功配置了。我直接抓包后save response做成文件，比大佬前几个commit里的sh/curl指令来的方便点。 另外，商店一旦变动templateid（就他们系统内等于完全重建了个临时dc配置），预加载也会失效。
> 
> 极速达的地理围墙我自己也不确定，只是瞎猜areablockid。地理围墙是我自己测出来的。我和朋友固定同一个dc覆盖，我离得远他离得近。封城后，我地址（5.4公里行程，非直线距离）在4月中旬还能配送，但5月前后，dc变动配置无法配送了；然后上海静默后，同一个dc第二次变更配置，他的地址（3.4公里行程，非直线距离）也无法配送了。
> 
> isSelected是因为有些东西并不想删出购物车，但本次姑且还不想买。亦或者有时帮亲戚买，也不想删除购物车。谢谢

还有一种方法，你可以试试，在山姆的添加地址接口，你将地址参数的中的`longitude`和`latitude`改成对应店铺的经纬度。添加一个实际描述地址和经纬度不同的地址。而山姆的配送范围和templateid都是根据经纬度来确定的。这样应该可以下单成功，单是配送不配送就不清除了。

**Comment by chqyhslwszds** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > 抢购还搞isSelected? 极速达dc地理围墙是什么？极速达dc的areablockid基本是固定的。
> 
> > > 你可以尝试下商店预加载，具体看在这里： #76
> 
> > 
> 
> > 上海各个dc的storetemplateid和areablockid已经变动了好几次了。我甚至已经抓包看到“xx静默（临时区块别占用）“的字样了。我甚至今天通过下单——地址写dc仓地址、详细地址写我自家地址强行下单。这样强行让人工发现并与我联系，最后小哥打电话和我说dc配送范围居然已经缩到1公里内了。
> 
> > 
> 
> > 我一直关注着大佬的项目，预加载其实我已经成功配置了。我直接抓包后save response做成文件，比大佬前几个commit里的sh/curl指令来的方便点。 另外，商店一旦变动templateid（就他们系统内等于完全重建了个临时dc配置），预加载也会失效。
> 
> > 
> 
> > 极速达的地理围墙我自己也不确定，只是瞎猜areablockid。地理围墙是我自己测出来的。我和朋友固定同一个dc覆盖，我离得远他离得近。封城后，我地址（5.4公里行程，非直线距离）在4月中旬还能配送，但5月前后，dc变动配置无法配送了；然后上海静默后，同一个dc第二次变更配置，他的地址（3.4公里行程，非直线距离）也无法配送了。
> 
> > 
> 
> > isSelected是因为有些东西并不想删出购物车，但本次姑且还不想买。亦或者有时帮亲戚买，也不想删除购物车。谢谢
> 
> 
> 
> 还有一种方法，你可以试试，在山姆的添加地址接口，你将地址参数的中的`longitude`和`latitude`改成对应店铺的经纬度。添加一个实际描述地址和对应经纬度不同的地址。而山姆的配送范围和templateid都是根据经纬度来确定的。这样应该可以下单成功，但是配送不配送就不清楚了。

测试成功

**Comment by chqyhslwszds** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > 抢购还搞isSelected? 极速达dc地理围墙是什么？极速达dc的areablockid基本是固定的。
> 
> > > 你可以尝试下商店预加载，具体看在这里： #76
> 
> > 
> 
> > 上海各个dc的storetemplateid和areablockid已经变动了好几次了。我甚至已经抓包看到“xx静默（临时区块别占用）“的字样了。我甚至今天通过下单——地址写dc仓地址、详细地址写我自家地址强行下单。这样强行让人工发现并与我联系，最后小哥打电话和我说dc配送范围居然已经缩到1公里内了。
> 
> > 
> 
> > 我一直关注着大佬的项目，预加载其实我已经成功配置了。我直接抓包后save response做成文件，比大佬前几个commit里的sh/curl指令来的方便点。 另外，商店一旦变动templateid（就他们系统内等于完全重建了个临时dc配置），预加载也会失效。
> 
> > 
> 
> > 极速达的地理围墙我自己也不确定，只是瞎猜areablockid。地理围墙是我自己测出来的。我和朋友固定同一个dc覆盖，我离得远他离得近。封城后，我地址（5.4公里行程，非直线距离）在4月中旬还能配送，但5月前后，dc变动配置无法配送了；然后上海静默后，同一个dc第二次变更配置，他的地址（3.4公里行程，非直线距离）也无法配送了。
> 
> > 
> 
> > isSelected是因为有些东西并不想删出购物车，但本次姑且还不想买。亦或者有时帮亲戚买，也不想删除购物车。谢谢
> 
> 
> 
> 还有一种方法，你可以试试，在山姆的添加地址接口，你将地址参数的中的`longitude`和`latitude`改成对应店铺的经纬度。添加一个实际描述地址和对应经纬度不同的地址。而山姆的配送范围和templateid都是根据经纬度来确定的。这样应该可以下单成功，但是配送不配送就不清楚了。

测试成功
