### ISSUE TITLE
请问刷新请求过于频繁，会不会被防火墙阻挡

### ISSUE THREAD

**Issue by JimmyABZ** [robGoods/sams#78]
请问刷新请求过于频繁，山姆的腾讯云WAF会不会暂时风控账号

**Comment by chqyhslwszds** [comment]
> 请问刷新请求过于频繁，山姆的腾讯云WAF会不会暂时风控账号

想多了，那么多筋膜枪大军在呢。
频繁取消订单也不会。
毕竟sams是收了会员费的。

**Comment by iscod** [comment]
> 请问刷新请求过于频繁，山姆的腾讯云WAF会不会暂时风控账号

可能封ip，不过重启下家里的路由器换个ip 就可以了，或者用vpn
