### ISSUE TITLE
找不到access token。。。

### ISSUE THREAD

**Issue by chendcblademaster** [robGoods/sams#8]
用Charles抓包，一条条找也没找到token，
手机端要进行什么操作才能找到山姆的token？能否给一个简易的步骤？

**Comment by DioneLJH** [comment]
我ios用stream抓的，但是运行显示token过期

**Comment by iscod** [comment]
> 我ios用stream抓的，但是运行显示token过期



> 用Charles抓包，一条条找也没找到token，
> 手机端要进行什么操作才能找到山姆的token？能否给一个简易的步骤？

Charles抓https需要证书，山姆app几乎每个请求都有token，你再仔细找找

**Comment by iscod** [comment]
> 我ios用stream抓的，但是运行显示token过期

stream感觉是个坑，我下载完第二天就删了

**Comment by DioneLJH** [comment]
> > 我ios用stream抓的，但是运行显示token过期
> 
> stream感觉是个坑，我下载完第二天就删了

我试试Charkes
