### ISSUE TITLE
完犊子了

### ISSUE THREAD

**Issue by chqyhslwszds** [robGoods/sams#80]
被封杀了貌似

**Comment by iscod** [comment]
?

**Comment by abelardwu** [comment]
刚被waf阻断了

**Comment by iscod** [comment]
> 刚被waf阻断了

路由器重启，换个ip 地址就行了

**Comment by abelardwu** [comment]
如果我用外网的vps，用国内的经纬度，会有检测经纬度导致的风险吗？

**Comment by chqyhslwszds** [comment]
> > 刚被waf阻断了
> 
> 
> 
> 路由器重启，换个ip 地址就行了

我是一个局域网开了两个号
重启猫之后只开了一个号正常
但今天被静态的地方太多、抢了个寂寞。

**Comment by iscod** [comment]
> 

一个号，正常抢就可以。基本都能抢到

**Comment by 981491887** [comment]
作者你好,我在cmd运行界面是这样子,自动跳到vscode去了 小白有点看不懂,可以帮忙看问题出在哪里么
![@ 7$1SVO@S5 `_NCE_BRNCQ](https://user-images.githubusercontent.com/46521111/168418725-b353e849-305e-4d04-8a42-a35785425718.png)
![D~VH13S)O1YWH9CUZPE}YR2](https://user-images.githubusercontent.com/46521111/168418727-cc6d9d3a-fcbe-4e27-8d27-f0a59772e254.png)

**Comment by 981491887** [comment]
作者,你好我部署了go环境,在main.go文件里" "位置处输入了我的token,然后在cmd运行了 显示成这样子了(刚抓取的token..  小白不太懂能帮忙看一下么
![DUF0A_)_A84@R6}`OF%VZSY](https://user-images.githubusercontent.com/46521111/168420097-ef5c1f0e-706f-4eb7-b74e-d4132550c172.png)
,
