### ISSUE TITLE
提交订单后下单失败

### ISSUE THREAD

**Issue by connermo** [robGoods/sams#87]
最近都是这样，不知道是什么原因？更新的github最新代码。谢谢！

########## 提交订单中【08:28:29】 ###########
配送时段: 2022/05/21 周六 10:00 - 13:00!
下单失败：当前配送时间段已约满，请重新选择配送时段

**Comment by chqyhslwszds** [comment]
没有放运力，全城配从1400-1415时间段刷满

**Comment by connermo** [comment]
收到，谢谢！
