### ISSUE TITLE
能问个小白问题吗？darwin或者.linux文件如何打开？

### ISSUE THREAD

**Issue by wesleyzz1982** [robGoods/sams#88]
没有看到.exe的可执行文件，是否需要在win下安装go语言环境才能打开。darwin文件？谢谢，抱歉计算机都还给老师了

**Comment by iscod** [comment]
> 没有看到.exe的可执行文件，是否需要在win下安装go语言环境才能打开。darwin文件？谢谢，抱歉计算机都还给老师了

darwin是mac系统下的，linux是linux系统。.exe我没编译

**Comment by iscod** [comment]
> > 没有看到.exe的可执行文件，是否需要在win下安装go语言环境才能打开。darwin文件？谢谢，抱歉计算机都还给老师了
> 
> darwin是mac系统下的，linux是linux系统，这两个系统的文件后缀名没影响，就是个标识。.exe我没编译

**Comment by YHSTP** [comment]
window下是不是需要安装GO环境来运行呢？有运行教程地址么？谢谢！

**Comment by sc1992** [comment]
> > 没有看到.exe的可执行文件，是否需要在win下安装go语言环境才能打开。darwin文件？谢谢，抱歉计算机都还给老师了
> 
> darwin是mac系统下的，linux是linux系统。.exe我没编译

怎么打开呢，还是打不开。
